-- Migration 036: Document new I4 VWAP and Volume Profile fields
-- These fields are stored in the i4 JSONB column of intelligence_features
-- No DDL changes required — JSONB is schema-flexible
--
-- New AnchoredVWAP fields (migrated from I3 to I4 in Plan 34-01):
--   session_vwap, session_vwap_dist_pct, swing_vwap, weekly_vwap,
--   above_session_vwap, above_swing_vwap, above_weekly_vwap, vwap_alignment_score,
--   avwap_upper_band, avwap_lower_band, swing_vwap_upper_band, swing_vwap_lower_band,
--   session_vwap_deviation_sigma, swing_vwap_deviation_sigma, session_vwap_deviation_velocity
--
-- New VolumeProfile fields (migrated from I5 to I4 in Plan 34-02):
--   nearest_hvn_level, nearest_hvn_dist_atr, nearest_lvn_level, in_lvn,
--   poc_price, vah, val, nearest_hvn_above, nearest_hvn_below,
--   nearest_lvn_above, nearest_lvn_below, poc_price_rolling, vah_rolling, val_rolling,
--   price_in_value_area, va_width_atr, distance_to_vah_atr, distance_to_val_atr
--
-- New I7 plugins consuming these fields (Plan 34-03):
--   trad_AnchoredVWAPReversion: uses session_vwap_deviation_sigma, session_vwap_deviation_velocity,
--                                avwap_upper_band, avwap_lower_band
--   trad_VWAPReclaim:           uses session_vwap (cross detection)
--   trad_POCRejection:          uses poc_price, va_width_atr
--   trad_HVNRejection:          uses nearest_hvn_above, nearest_hvn_below, nearest_hvn_dist_atr
--   trad_LVNBreakout:           uses in_lvn, nearest_hvn_above, nearest_hvn_below,
--                                nearest_lvn_above, nearest_lvn_below
--
-- Verification: after pipeline runs, confirm fields are populated:
-- SELECT i4->>'poc_price', i4->>'session_vwap_deviation_sigma'
-- FROM intelligence_features WHERE symbol='ES' ORDER BY feature_ts DESC LIMIT 1;

SELECT 'Migration 037: VWAP + Volume Profile I4 fields documented' AS status;
