-- Migration 123: Full plugin parameter store migration.
--
-- Seeds all hard-coded detection thresholds, confidence weights, and zone geometry
-- constants across I7 plugins + shared utilities into the parameter store.
-- All seed values match current hard-coded constants exactly (zero behaviour change at rollout).
-- All marked [initial_estimate] or [conventional] -- none empirically validated.
-- ML discovery will replace them once n >= 100, p < 0.05 per instrument/regime cell.
--
-- Provenance: see docs/foundation/parameter-store.md#description-field.

-- schema entries

INSERT INTO config_schema (config_key, value_type, default_value, min_value, max_value, description) VALUES
('threshold.global.min_regime_weight', 'float', '0.30', 0.0, 1.0,
 '[initial_estimate] Min HMM regime weight for the dual gate applied to all I7 plugins. Used by get_min_regime_weight() in confidence_utils. ML learning target.'),
('threshold.global.min_ctf_score', 'float', '0.25', 0.0, 1.0,
 '[initial_estimate] Min abs(ctf_score) for the dual gate applied to all I7 plugins. Used by get_min_ctf_score() in confidence_utils. ML learning target.'),
('threshold.volume_profile.div_min', 'float', '0.30', 0.0, 1.0,
 '[conventional] Min RSI divergence confidence for reversal gate in check_reversal_gate(). Applies to both HVN and POC rejection. ML learning target per instrument.'),
('threshold.volume_profile.stoch_oversold', 'float', '30.0', 0.0, 50.0,
 '[conventional] Stochastic %K oversold threshold -- momentum confirmation for long reversals. Textbook 30. ML learning target.'),
('threshold.volume_profile.stoch_overbought', 'float', '70.0', 50.0, 100.0,
 '[conventional] Stochastic %K overbought threshold -- momentum confirmation for short reversals. Textbook 70. ML learning target.'),
('threshold.hvn_rejection.proximity_atr', 'float', '0.30', 0.05, 2.0,
 '[initial_estimate] Max ATR-normalised distance from HVN for proximity gate. Instrument-specific calibration pending. ML learning target.'),
('threshold.poc_rejection.proximity_atr', 'float', '0.30', 0.05, 2.0,
 '[initial_estimate] Max ATR-normalised distance from POC for proximity gate. Instrument-specific calibration pending. ML learning target.'),
('threshold.session_extremes.proximity_atr', 'float', '0.30', 0.05, 2.0,
 '[initial_estimate] Max ATR-normalised distance from Asian session H/L. ML learning target.'),
('threshold.session_extremes.rsi_oversold', 'float', '35.0', 20.0, 50.0,
 '[conventional] RSI oversold threshold for long setups at session low. Textbook ~30-35. ML target.'),
('threshold.session_extremes.rsi_overbought', 'float', '65.0', 50.0, 80.0,
 '[conventional] RSI overbought threshold for short setups at session high. Textbook ~65-70. ML target.'),
('threshold.liquidity_hunt.significance_min', 'float', '0.60', 0.0, 1.0,
 '[initial_estimate] Min liquidity significance score for LiquidityHuntPlugin gate. ML target.'),
('threshold.gap_analysis.min_gap_atr', 'float', '0.80', 0.1, 5.0,
 '[initial_estimate] Min gap size in ATR multiples for GapAnalysisSetupPlugin. ML target.'),
('threshold.gap_analysis.continuation_atr', 'float', '1.00', 0.1, 5.0,
 '[initial_estimate] ATR threshold distinguishing continuation vs. reversal gaps. ML target.'),
('threshold.gap_analysis.volume_confirm_ratio', 'float', '1.50', 1.0, 5.0,
 '[initial_estimate] Min volume ratio for gap continuation confirmation. ML target.'),
('threshold.mtf_alignment.ctf_score_min', 'float', '0.70', 0.0, 1.0,
 '[initial_estimate] Min abs(ctf_score) for MTFAlignmentPlugin -- stricter than global gate (0.25) because MTF setup demands strong cross-TF signal. ML target.'),
('threshold.regime_transition.cp_min', 'float', '0.50', 0.0, 1.0,
 '[conventional] Min changepoint probability for RegimeTransitionPlugin. ML target.'),
('threshold.dual_divergence.ofi_div_min', 'float', '1.00', 0.0, 5.0,
 '[initial_estimate] Min abs(ofi_divergence) for DualDivergencePlugin. ML target per instrument.'),
('threshold.dual_divergence.cvd_div_min', 'float', '1.00', 0.0, 5.0,
 '[initial_estimate] Min abs(cvd_divergence) for DualDivergencePlugin. ML target per instrument.'),
('threshold.orb.vol_expansion_mult', 'float', '1.50', 1.0, 5.0,
 '[initial_estimate] Volume expansion multiplier gate shared by ORB15Plugin and ORB30Plugin. ML target.'),
('threshold.vcp.min_contractions', 'int', '3', 2, 10,
 '[conventional] Minimum contraction bars before VCPPlugin expansion fire. Wyckoff convention. ML target.'),
('threshold.vcp.vol_expansion_mult', 'float', '1.20', 1.0, 3.0,
 '[initial_estimate] Volume expansion multiplier for VCPPlugin breakout bar. ML target.'),
('threshold.ofi_divergence.min_persistence_bars', 'int', '2', 1, 10,
 '[rca_analysis] Minimum consecutive bars of OFI/price divergence before OFIDivergencePlugin fires. Phase 118 starting guess. ML target.'),
('threshold.aggregator.regime_tiebreak', 'float', '0.40', 0.0, 1.0,
 '[initial_estimate] Min |trend_regime| to use regime direction in aggregator fallback tiebreak. ML target.'),
('feature.volume_zscore.window', 'int', '20', 5, 200,
 '[conventional] Rolling window for VolumeZscorePlugin z-score calculation. ML target.'),
('weights.gap_analysis.geo', 'float', '0.40', 0.0, 1.0,
 '[initial_estimate] Gap geometry score weight in GapAnalysisSetupPlugin raw_conf. ML learning target.'),
('weights.gap_analysis.vol', 'float', '0.25', 0.0, 1.0,
 '[initial_estimate] Volume score weight in GapAnalysisSetupPlugin raw_conf. ML learning target.'),
('weights.gap_analysis.timing', 'float', '0.20', 0.0, 1.0,
 '[initial_estimate] Session timing score weight in GapAnalysisSetupPlugin raw_conf. ML learning target.'),
('weights.gap_analysis.type', 'float', '0.15', 0.0, 1.0,
 '[initial_estimate] Gap type score weight in GapAnalysisSetupPlugin raw_conf. ML learning target.'),
('weights.mean_reversion.rsi_extreme', 'float', '0.30', 0.0, 1.0,
 '[initial_estimate] RSI extreme score weight in MeanReversionPlugin raw_conf. ML learning target.'),
('weights.mean_reversion.div_score', 'float', '0.30', 0.0, 1.0,
 '[initial_estimate] Divergence score weight in MeanReversionPlugin raw_conf. ML learning target.'),
('weights.mean_reversion.vol_stability', 'float', '0.20', 0.0, 1.0,
 '[initial_estimate] Volatility stability weight in MeanReversionPlugin raw_conf. ML learning target.'),
('weights.mean_reversion.sr_proximity', 'float', '0.20', 0.0, 1.0,
 '[initial_estimate] S/R proximity weight in MeanReversionPlugin raw_conf. ML learning target.'),
('weights.momentum_breakout.roc', 'float', '0.40', 0.0, 1.0,
 '[initial_estimate] ROC score weight in MomentumBreakoutPlugin raw_conf. ML learning target.'),
('weights.momentum_breakout.vol', 'float', '0.35', 0.0, 1.0,
 '[initial_estimate] Volume score weight in MomentumBreakoutPlugin raw_conf. ML learning target.'),
('weights.momentum_breakout.break_margin', 'float', '0.25', 0.0, 1.0,
 '[initial_estimate] Structure break margin weight in MomentumBreakoutPlugin. ML learning target.'),
('weights.squeeze_expansion.squeeze_bars', 'float', '0.35', 0.0, 1.0,
 '[initial_estimate] Squeeze duration score weight in SqueezeExpansionPlugin. ML learning target.'),
('weights.squeeze_expansion.vol_expansion', 'float', '0.35', 0.0, 1.0,
 '[initial_estimate] Volume expansion score weight in SqueezeExpansionPlugin. ML learning target.'),
('weights.squeeze_expansion.momentum', 'float', '0.30', 0.0, 1.0,
 '[initial_estimate] Momentum clarity score weight in SqueezeExpansionPlugin. ML learning target.'),
('weights.vwap_reclaim.vol', 'float', '0.30', 0.0, 1.0,
 '[initial_estimate] Volume score weight in VWAPReclaimPlugin raw_conf. ML learning target.'),
('weights.vwap_reclaim.duration', 'float', '0.30', 0.0, 1.0,
 '[initial_estimate] Duration-below-VWAP score weight in VWAPReclaimPlugin. ML learning target.'),
('weights.vwap_reclaim.trend_align', 'float', '0.20', 0.0, 1.0,
 '[initial_estimate] Trend alignment weight in VWAPReclaimPlugin raw_conf. ML learning target.'),
('weights.vwap_reclaim.sr_proximity', 'float', '0.20', 0.0, 1.0,
 '[initial_estimate] S/R proximity weight in VWAPReclaimPlugin raw_conf. ML learning target.'),
('weights.liquidity_sweep.base_conf', 'float', '0.40', 0.0, 1.0,
 '[initial_estimate] Base confidence (floor) in LiquiditySweepReclaimPlugin. ML learning target.'),
('weights.liquidity_sweep.depth_scale', 'float', '0.20', 0.0, 1.0,
 '[initial_estimate] Sweep depth scale factor in LiquiditySweepReclaimPlugin. ML learning target.'),
('weights.supply_demand.base_conf', 'float', '0.35', 0.0, 1.0,
 '[initial_estimate] Base confidence (floor) in SupplyDemandSetupPlugin. ML learning target.'),
('weights.supply_demand.freshness_scale', 'float', '0.23', 0.0, 1.0,
 '[initial_estimate] Zone freshness linear ramp scale in SupplyDemandSetupPlugin. ML learning target.'),
('feature.zone_engine.cluster_radius_atr', 'float', '0.50', 0.1, 3.0,
 '[initial_estimate] ATR-normalised radius for zone cluster formation in ZoneEngine. ML target.'),
('feature.zone_engine.zone_buffer_atr', 'float', '0.15', 0.01, 1.0,
 '[initial_estimate] ATR-normalised buffer added to zone bounds in ZoneEngine. ML target.'),
('feature.zone_engine.min_width_atr', 'float', '0.25', 0.01, 2.0,
 '[initial_estimate] Minimum zone width in ATR multiples for cluster zones. ML target.'),
('feature.zone_engine.single_level_radius_atr', 'float', '0.25', 0.01, 2.0,
 '[initial_estimate] ATR radius for single-level zone fallback in ZoneEngine. ML target.'),
('weights.zone_engine.strength', 'float', '0.60', 0.0, 1.0,
 '[initial_estimate] Level strength weight in single-level zone scoring. ML target.'),
('weights.zone_engine.proximity', 'float', '0.40', 0.0, 1.0,
 '[initial_estimate] Price proximity weight in single-level zone scoring. ML target.')
ON CONFLICT (config_key) DO NOTHING;

-- live state entries

INSERT INTO config_state (config_key, config_value, version) VALUES
('threshold.global.min_regime_weight',          '0.30', 1),
('threshold.global.min_ctf_score',              '0.25', 1),
('threshold.volume_profile.div_min',            '0.30', 1),
('threshold.volume_profile.stoch_oversold',     '30.0', 1),
('threshold.volume_profile.stoch_overbought',   '70.0', 1),
('threshold.hvn_rejection.proximity_atr',       '0.30', 1),
('threshold.poc_rejection.proximity_atr',       '0.30', 1),
('threshold.session_extremes.proximity_atr',    '0.30', 1),
('threshold.session_extremes.rsi_oversold',     '35.0', 1),
('threshold.session_extremes.rsi_overbought',   '65.0', 1),
('threshold.liquidity_hunt.significance_min',   '0.60', 1),
('threshold.gap_analysis.min_gap_atr',          '0.80', 1),
('threshold.gap_analysis.continuation_atr',     '1.00', 1),
('threshold.gap_analysis.volume_confirm_ratio', '1.50', 1),
('threshold.mtf_alignment.ctf_score_min',       '0.70', 1),
('threshold.regime_transition.cp_min',          '0.50', 1),
('threshold.dual_divergence.ofi_div_min',       '1.00', 1),
('threshold.dual_divergence.cvd_div_min',       '1.00', 1),
('threshold.orb.vol_expansion_mult',            '1.50', 1),
('threshold.vcp.min_contractions',              '3',    1),
('threshold.vcp.vol_expansion_mult',            '1.20', 1),
('threshold.ofi_divergence.min_persistence_bars','2',   1),
('threshold.aggregator.regime_tiebreak',        '0.40', 1),
('feature.volume_zscore.window',                '20',   1),
('weights.gap_analysis.geo',                    '0.40', 1),
('weights.gap_analysis.vol',                    '0.25', 1),
('weights.gap_analysis.timing',                 '0.20', 1),
('weights.gap_analysis.type',                   '0.15', 1),
('weights.mean_reversion.rsi_extreme',          '0.30', 1),
('weights.mean_reversion.div_score',            '0.30', 1),
('weights.mean_reversion.vol_stability',        '0.20', 1),
('weights.mean_reversion.sr_proximity',         '0.20', 1),
('weights.momentum_breakout.roc',               '0.40', 1),
('weights.momentum_breakout.vol',               '0.35', 1),
('weights.momentum_breakout.break_margin',      '0.25', 1),
('weights.squeeze_expansion.squeeze_bars',      '0.35', 1),
('weights.squeeze_expansion.vol_expansion',     '0.35', 1),
('weights.squeeze_expansion.momentum',          '0.30', 1),
('weights.vwap_reclaim.vol',                    '0.30', 1),
('weights.vwap_reclaim.duration',               '0.30', 1),
('weights.vwap_reclaim.trend_align',            '0.20', 1),
('weights.vwap_reclaim.sr_proximity',           '0.20', 1),
('weights.liquidity_sweep.base_conf',           '0.40', 1),
('weights.liquidity_sweep.depth_scale',         '0.20', 1),
('weights.supply_demand.base_conf',             '0.35', 1),
('weights.supply_demand.freshness_scale',       '0.23', 1),
('feature.zone_engine.cluster_radius_atr',      '0.50', 1),
('feature.zone_engine.zone_buffer_atr',         '0.15', 1),
('feature.zone_engine.min_width_atr',           '0.25', 1),
('feature.zone_engine.single_level_radius_atr', '0.25', 1),
('weights.zone_engine.strength',                '0.60', 1),
('weights.zone_engine.proximity',               '0.40', 1)
ON CONFLICT (config_key) DO NOTHING;

-- seed config_history

INSERT INTO config_history (timestamp, config_key, version, config_value, changed_by, reason)
VALUES
(NOW(), 'threshold.global.min_regime_weight',           1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.global.min_ctf_score',               1, '0.25', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.volume_profile.div_min',             1, '0.30', 'conventional',     'Migration 129 seed'),
(NOW(), 'threshold.volume_profile.stoch_oversold',      1, '30.0', 'conventional',     'Migration 129 seed'),
(NOW(), 'threshold.volume_profile.stoch_overbought',    1, '70.0', 'conventional',     'Migration 129 seed'),
(NOW(), 'threshold.hvn_rejection.proximity_atr',        1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.poc_rejection.proximity_atr',        1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.session_extremes.proximity_atr',     1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.session_extremes.rsi_oversold',      1, '35.0', 'conventional',     'Migration 129 seed'),
(NOW(), 'threshold.session_extremes.rsi_overbought',    1, '65.0', 'conventional',     'Migration 129 seed'),
(NOW(), 'threshold.liquidity_hunt.significance_min',    1, '0.60', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.gap_analysis.min_gap_atr',           1, '0.80', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.gap_analysis.continuation_atr',      1, '1.00', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.gap_analysis.volume_confirm_ratio',  1, '1.50', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.mtf_alignment.ctf_score_min',        1, '0.70', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.regime_transition.cp_min',           1, '0.50', 'conventional',     'Migration 129 seed'),
(NOW(), 'threshold.dual_divergence.ofi_div_min',        1, '1.00', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.dual_divergence.cvd_div_min',        1, '1.00', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.orb.vol_expansion_mult',             1, '1.50', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.vcp.min_contractions',               1, '3',    'conventional',     'Migration 129 seed'),
(NOW(), 'threshold.vcp.vol_expansion_mult',             1, '1.20', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'threshold.ofi_divergence.min_persistence_bars',1, '2',    'rca_analysis',     'Migration 129 seed'),
(NOW(), 'threshold.aggregator.regime_tiebreak',         1, '0.40', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'feature.volume_zscore.window',                 1, '20',   'conventional',     'Migration 129 seed'),
(NOW(), 'weights.gap_analysis.geo',                     1, '0.40', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.gap_analysis.vol',                     1, '0.25', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.gap_analysis.timing',                  1, '0.20', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.gap_analysis.type',                    1, '0.15', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.mean_reversion.rsi_extreme',           1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.mean_reversion.div_score',             1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.mean_reversion.vol_stability',         1, '0.20', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.mean_reversion.sr_proximity',          1, '0.20', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.momentum_breakout.roc',                1, '0.40', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.momentum_breakout.vol',                1, '0.35', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.momentum_breakout.break_margin',       1, '0.25', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.squeeze_expansion.squeeze_bars',       1, '0.35', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.squeeze_expansion.vol_expansion',      1, '0.35', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.squeeze_expansion.momentum',           1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.vwap_reclaim.vol',                     1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.vwap_reclaim.duration',                1, '0.30', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.vwap_reclaim.trend_align',             1, '0.20', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.vwap_reclaim.sr_proximity',            1, '0.20', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.liquidity_sweep.base_conf',            1, '0.40', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.liquidity_sweep.depth_scale',          1, '0.20', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.supply_demand.base_conf',              1, '0.35', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.supply_demand.freshness_scale',        1, '0.23', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'feature.zone_engine.cluster_radius_atr',       1, '0.50', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'feature.zone_engine.zone_buffer_atr',          1, '0.15', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'feature.zone_engine.min_width_atr',            1, '0.25', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'feature.zone_engine.single_level_radius_atr',  1, '0.25', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.zone_engine.strength',                 1, '0.60', 'initial_estimate', 'Migration 129 seed'),
(NOW(), 'weights.zone_engine.proximity',                1, '0.40', 'initial_estimate', 'Migration 129 seed');
