-- Migration 164: Ensemble tables + APR seeds for Phase 139 Ensemble + Alpha Emission.
--
-- Creates three v3.0 tables:
--   ensemble_weights   — IC-Sharpe-weighted feature weights per (symbol, tf, regime, weight_version)
--   ensemble_alpha     — per-bar composite alpha scores (hypertable)
--   alpha_events       — alpha emission events (hypertable, composite PK for TimescaleDB)
--
-- Seeds 13 APR keys in config_schema + config_state:
--   alpha.ensemble.*  — 9 keys (weight derivation, cluster deflation, CI acknowledgement)
--   alpha.quant.threshold.*  — 4 keys (per-TF emission thresholds in composite z-score units)
--
-- Key design notes:
--
--   alpha_events PRIMARY KEY (event_id, bar_ts) — composite PK including bar_ts is required
--   for TimescaleDB hypertable enforcement across chunks. The hypertable partition column
--   (bar_ts) must appear in the primary key. event_id is the SHA-256 content key generated
--   by BaseBatch.content_key(symbol, tf, str(bar_ts_ns), ensemble_version)[:32].
--
--   alpha_events.top_features NOT NULL — the architecture traceability invariant requires
--   top_features never be null on an emission. The alpha emitter must always populate this
--   JSONB with at least the top min(n_features, top_features_count) contributors.
--
--   alpha_events.direction CHECK ('long','short') — the ensemble emitter determines direction
--   from the IC sign of the dominant feature cluster; both directions are valid emissions.
--
--   alpha.ensemble.min_passing_features = 5, not 3 — mathematical feasibility constraint:
--   5 × max_weight(0.20) = 1.0, which is the minimum for a valid normalized weight vector
--   under the per-feature cap. Values below 5 with max_weight=0.20 cannot produce a valid
--   normalized weight vector.
--
--   alpha.quant.threshold.* — initial estimates in composite z-score units. Higher bars for
--   shorter TFs reflect greater noise and higher transaction cost per unit time. Recalibrate
--   post corpus run by computing E[return | alpha_score > threshold] from ensemble_alpha
--   joined to forward_returns. These are NOT ML learning targets.
--
-- All statements idempotent: CREATE TABLE IF NOT EXISTS, ON CONFLICT DO NOTHING.
-- Safe to re-run.

-- -------------------------------------------------------------------------
-- Section 1: DDL — three tables
-- -------------------------------------------------------------------------

-- ensemble_weights: per-feature weights per (symbol, tf, regime, weight_version).
-- NOT a hypertable — dimension is weight_version (a version tag), not time.
CREATE TABLE IF NOT EXISTS ensemble_weights (
    symbol              text             NOT NULL,
    tf                  text             NOT NULL,
    regime              text             NOT NULL,
    weight_version      text             NOT NULL,   -- e.g. 'v1' or '2024-01-15'
    feature_name        text             NOT NULL,
    ic_sharpe           double precision,            -- IC Sharpe used for this weight
    raw_weight          double precision,            -- before cap/renorm
    weight              double precision NOT NULL,   -- after per-feature cap + renorm
    lookahead_bars      integer         NOT NULL,    -- which lookahead was selected
    effective_n         double precision,            -- effective N of the full weight vector (stored once per symbol/tf/regime/version)
    computed_at         timestamptz      NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol, tf, regime, weight_version, feature_name)
);

CREATE INDEX IF NOT EXISTS ensemble_weights_lookup_idx
    ON ensemble_weights (symbol, tf, regime, weight_version);

-- ensemble_alpha: per-bar composite alpha scores. TimescaleDB hypertable by bar_ts.
CREATE TABLE IF NOT EXISTS ensemble_alpha (
    symbol              text             NOT NULL,
    tf                  text             NOT NULL,
    bar_ts              timestamptz      NOT NULL,
    weight_version      text             NOT NULL,
    regime              text,                        -- regime at bar_ts
    alpha_score         double precision NOT NULL,
    alpha_ci_lower      double precision,
    alpha_ci_upper      double precision,
    effective_n         double precision,
    n_features_active   integer,
    computed_at         timestamptz      NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol, tf, bar_ts, weight_version)
);

SELECT create_hypertable(
    'ensemble_alpha',
    'bar_ts',
    chunk_time_interval => INTERVAL '3 months',
    if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS ensemble_alpha_symbol_tf_idx
    ON ensemble_alpha (symbol, tf, bar_ts DESC);

-- alpha_events: alpha emission events — one row per emission crossing the threshold.
-- Composite PRIMARY KEY (event_id, bar_ts) is required for TimescaleDB hypertable:
-- the partition column (bar_ts) must appear in the primary key.
-- event_id is generated by BaseBatch.content_key(symbol, tf, str(bar_ts_ns), ensemble_version)[:32].
-- top_features NOT NULL — traceability invariant; emitter must always populate this field.
-- direction CHECK ('long','short') — both directions are valid alpha emissions.
CREATE TABLE IF NOT EXISTS alpha_events (
    event_id            text             NOT NULL,   -- SHA-256 content key (32 hex chars)
    symbol              text             NOT NULL,
    tf                  text             NOT NULL,
    bar_ts              timestamptz      NOT NULL,
    ensemble_version    text             NOT NULL,
    weight_version      text             NOT NULL,
    regime              text,
    alpha_score         double precision NOT NULL,
    alpha_ci_lower      double precision,
    alpha_ci_upper      double precision,
    effective_n         double precision,
    n_features_active   integer,
    emission_threshold  double precision,
    direction           text             NOT NULL CHECK (direction IN ('long', 'short')),
    top_features        jsonb            NOT NULL,   -- {feature_name: contribution_value}, NOT NULL by traceability invariant
    emitted_at          timestamptz      NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, bar_ts)
);

SELECT create_hypertable(
    'alpha_events',
    'bar_ts',
    chunk_time_interval => INTERVAL '3 months',
    if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS alpha_events_symbol_tf_idx
    ON alpha_events (symbol, tf, bar_ts DESC);

-- -------------------------------------------------------------------------
-- Section 2: config_schema entries (13 keys)
-- Column set mirrors migration 161: config_key, value_type, default_value,
-- min_value, max_value, description. Provenance tags in description.
-- -------------------------------------------------------------------------

INSERT INTO config_schema (config_key, value_type, default_value, min_value, max_value, description) VALUES
(
    'alpha.ensemble.max_feature_weight',
    'float',
    '0.20',
    0.05, 1.0,
    '[conventional] Per-feature weight cap in IC Sharpe weight derivation. After normalizing '
    'IC Sharpe values to sum to 1.0, any single feature''s weight is capped at this value via '
    'iterative proportional redistribution to uncapped features. 0.20 is the conventional '
    'maximum diversification constraint in factor model construction — prevents any single '
    'predictor from dominating the ensemble regardless of IC Sharpe magnitude. '
    'NOT an ML learning target.'
),
(
    'alpha.ensemble.effective_n_gate',
    'float',
    '3.0',
    1.0, 20.0,
    '[initial_estimate] Minimum effective N (inverse HHI of weights = 1/sum(w^2)) required '
    'before alpha emission is permitted. With 61 features and a 0.20 cap, max effective_N '
    'is 5. Gate of 3.0 ensures the ensemble has at least 3 effective independent predictors. '
    'An ensemble of 1 effective feature is not ensemble alpha — it is a single-factor bet. '
    'Recalibrate post corpus run by examining the empirical distribution of effective_N '
    'across (symbol, tf, regime) strata. NOT an ML learning target.'
),
(
    'alpha.ensemble.weight_version',
    'str',
    'v1',
    NULL, NULL,
    '[operator_controlled] Version tag for weight snapshots in ensemble_weights. Bump this '
    'to trigger a fresh weight solve without deleting old weights — old rows remain queryable '
    'for comparison. Format: ''v1'', ''v2'', or a date string like ''2024-01-15''. '
    'NOT an ML learning target.'
),
(
    'alpha.ensemble.lookahead_selection',
    'str',
    'max_ic_sharpe',
    NULL, NULL,
    '[initial_estimate] Strategy for selecting the single lookahead per feature per '
    '(symbol, tf, regime) during feature selection. ''max_ic_sharpe'' selects the lookahead '
    'with the highest IC Sharpe (IC stability over time), which is more robust than selecting '
    'on raw IC value. Tie-break: shorter lookahead wins (faster convergence, less noise). '
    'NOT an ML learning target.'
),
(
    'alpha.ensemble.min_passing_features',
    'int',
    '5',
    1, 61,
    '[initial_estimate] Minimum number of features with passes_walkforward=true required '
    'per (symbol, tf, regime) stratum to proceed with ensemble weight derivation. '
    'Mathematical feasibility constraint: with max_feature_weight=0.20, the minimum is 5 '
    'because 5 × 0.20 = 1.0 — the smallest number of features that can produce a valid '
    'normalized weight vector under the per-feature cap. Values below 5 with '
    'max_weight=0.20 cannot produce a valid weight vector. Strata below this threshold '
    'are skipped (no rows written to ensemble_weights or ensemble_alpha). '
    'NOT an ML learning target.'
),
(
    'alpha.ensemble.max_cluster_correlation',
    'float',
    '0.80',
    0.10, 0.99,
    '[initial_estimate] Pairwise Ledoit-Wolf correlation threshold above which two features '
    'are considered the same cluster for cluster deflation purposes. Features exceeding this '
    'threshold share weight within the cluster; the cluster''s total weight is then capped '
    'at alpha.ensemble.max_cluster_weight. Prevents double-counting when multiple momentum '
    'z-scores or similar features are collinear (e.g. momentum_z_fast, momentum_z_mid, '
    'momentum_z_slow may all have corr > 0.80). Recalibrate by examining the LW correlation '
    'matrix post corpus run. NOT an ML learning target.'
),
(
    'alpha.ensemble.max_cluster_weight',
    'float',
    '0.40',
    0.10, 1.0,
    '[initial_estimate] Maximum total weight a correlated cluster can receive after LW '
    'cluster deflation. A cluster of 3 highly-correlated momentum features will be capped '
    'at 0.40 total regardless of how many features it contains or their individual IC '
    'Sharpe values. Prevents momentum-factor concentration even when IC Sharpe for momentum '
    'features dominates the full feature universe. NOT an ML learning target.'
),
(
    'alpha.ensemble.top_features_count',
    'int',
    '10',
    1, 61,
    '[operator_controlled] Number of top-contributing features to include in '
    'alpha_events.top_features JSONB. Features ranked by abs(weight * feature_value) '
    'descending after cluster deflation. Default 10 balances traceability with payload '
    'size. Increase to capture more attribution detail; decrease to reduce payload size. '
    'NOT an ML learning target.'
),
(
    'alpha.ensemble.ci_independence_assumption',
    'str',
    'acknowledged',
    NULL, NULL,
    '[operator_controlled] Sentinel that confirms the CI propagation formula '
    '(var = dot(weights**2, sigma_ic**2)) assumes independent IC estimation errors '
    'across features. Correlated feature clusters produce correlated IC estimates; '
    'actual CI width is wider than computed. Cluster deflation '
    '(alpha.ensemble.max_cluster_correlation, alpha.ensemble.max_cluster_weight) '
    'mitigates this at the weight level. Full fix (var = w^T Sigma_IC w using full '
    'LW covariance of IC errors) is deferred pending corpus calibration. This key '
    'forces a conscious confirmation that the approximation is intentional. The value '
    '''acknowledged'' must be present for the alpha emitter to proceed. '
    'NOT an ML learning target.'
),
(
    'alpha.quant.threshold.5m',
    'float',
    '1.5',
    0.1, 5.0,
    '[initial_estimate] Alpha emission threshold for 5m timeframe in composite z-score '
    'units. The alpha score is sum(w_i * z_i) where z_i are already z-scored features — '
    'this threshold is in the natural units of that composite (not in return units). '
    'Higher bar for short TF: more noise, higher transaction cost per unit time. '
    'Recalibrate post corpus run by computing E[return | alpha_score > threshold] from '
    'ensemble_alpha joined to forward_returns, then set threshold so expected return '
    'exceeds transaction cost (typically 5-10 bps for liquid ETFs at 5m). '
    'NOT an ML learning target.'
),
(
    'alpha.quant.threshold.15m',
    'float',
    '1.2',
    0.1, 5.0,
    '[initial_estimate] Alpha emission threshold for 15m timeframe in composite z-score '
    'units. Lower bar than 5m: longer holding periods reduce transaction cost per unit '
    'time, permitting lower alpha confidence for economic viability. '
    'Recalibrate post corpus run (see alpha.quant.threshold.5m for methodology). '
    'NOT an ML learning target.'
),
(
    'alpha.quant.threshold.1h',
    'float',
    '1.0',
    0.1, 5.0,
    '[initial_estimate] Alpha emission threshold for 1h timeframe in composite z-score '
    'units. Lower bar than 15m: 1h holding periods further reduce transaction cost '
    'per unit time. Approximately one composite standard deviation from zero as a '
    'conservative initial estimate. '
    'Recalibrate post corpus run (see alpha.quant.threshold.5m for methodology). '
    'NOT an ML learning target.'
),
(
    'alpha.quant.threshold.1d',
    'float',
    '0.8',
    0.1, 5.0,
    '[initial_estimate] Alpha emission threshold for 1d timeframe in composite z-score '
    'units. Lowest bar: daily holding periods minimize transaction cost per unit time '
    'and allow more persistent alpha with lower instantaneous signal strength. '
    'Recalibrate post corpus run (see alpha.quant.threshold.5m for methodology). '
    'NOT an ML learning target.'
)
ON CONFLICT (config_key) DO NOTHING;

-- -------------------------------------------------------------------------
-- Section 3: config_state entries (seed values match defaults above)
-- -------------------------------------------------------------------------

INSERT INTO config_state (config_key, config_value, version) VALUES
('alpha.ensemble.max_feature_weight',        '0.20',          1),
('alpha.ensemble.effective_n_gate',          '3.0',           1),
('alpha.ensemble.weight_version',            'v1',            1),
('alpha.ensemble.lookahead_selection',       'max_ic_sharpe', 1),
('alpha.ensemble.min_passing_features',      '5',             1),
('alpha.ensemble.max_cluster_correlation',   '0.80',          1),
('alpha.ensemble.max_cluster_weight',        '0.40',          1),
('alpha.ensemble.top_features_count',        '10',            1),
('alpha.ensemble.ci_independence_assumption','acknowledged',   1),
('alpha.quant.threshold.5m',                 '1.5',           1),
('alpha.quant.threshold.15m',                '1.2',           1),
('alpha.quant.threshold.1h',                 '1.0',           1),
('alpha.quant.threshold.1d',                 '0.8',           1)
ON CONFLICT (config_key) DO NOTHING;
