-- Migration 216: Canary / Control Predictor columns — Phase 143.1 Plan 02 (todo 068)
--
-- Adds 5 genuine canary/control FeatureVector fields so a corpus-run integrity
-- assertion can catch a broken IC-measurement pipeline directly (negative
-- controls that clear a significance gate, or a positive control that fails
-- to). Component D of Phase 143.1 — Component C's (e-values pilot) dependency.
--
-- Cannot be "registry rows only" (RESEARCH.md Pitfall 6): FeatureRegistryService.load()/
-- load_sync() enforce a hard row-count-equals-len(FeatureVector fields) gate plus an
-- exact name-set-equality check in ic_engine.py/ensemble_trainer.py — adding registry
-- rows without matching FeatureVector dataclass fields (schemas.py + feature_factory.py,
-- already shipped this plan) would crash both at startup. This migration:
--   1. ALTERs feature_registry: adds is_control + control_expectation columns, extends
--      the group_name CHECK to admit 'control'.
--   2. ALTERs feature_vectors: adds the 5 canary columns.
--   3. INSERTs 5 feature_registry rows (is_control=true, status='candidate' — never
--      promoted, second line of defense beyond is_control alone).
--   4. INSERTs the alpha.ic.canary_rng_seed APR key (first real reader:
--      feature_factory.py's FeatureFactoryConfig.canary_rng_seed).
--
-- Row count after this migration: 150 + 5 = 155, matching the post-canary
-- FeatureVector field count (_REGISTRY_ROW_COUNT auto-derives from
-- dataclasses.fields(FeatureVector), no manual count to keep in sync).
--
-- Migration numbering note: 221 was already claimed by a concurrent session's
-- alpha_frames_compression migration; 222 was claimed by this phase's own Plan 01
-- (222_reactivate_bootstrap_ci_apr_keys.sql). 223 is the verified next-free number
-- as of this plan's execution (see todo 095 — directory-split collision risk).

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. feature_registry: is_control / control_expectation columns + extended
--    group_name CHECK
-- ---------------------------------------------------------------------------

ALTER TABLE feature_registry
    ADD COLUMN IF NOT EXISTS is_control boolean NOT NULL DEFAULT false;

ALTER TABLE feature_registry
    ADD COLUMN IF NOT EXISTS control_expectation text;

COMMENT ON COLUMN feature_registry.is_control IS
    'true for canary/control FeatureVector fields (Phase 143.1 Plan 02, todo 068). '
    'Excluded from ensemble eligibility via status=''candidate'' (never promoted) as a '
    'second line of defense beyond this flag alone. Iterated by '
    'ops_canary_integrity_assert.py to enforce the corpus-run integrity gate.';

COMMENT ON COLUMN feature_registry.control_expectation IS
    'NULL for non-control features. ''negative_control'' = must never clear the IC '
    'significance gate (noise/constant/near-constant canaries). ''positive_control'' = '
    'must clear it spectacularly (the acausal-placebo look-ahead canary) — proves the '
    'pipeline can detect contamination when it is genuinely present.';

-- group_name CHECK: drop and re-add with 'control' appended. Exact constraint name
-- verified live (feature_registry_group_name_check) — auto-generated by Postgres for
-- the inline column CHECK in migration 172, not explicitly named there.
ALTER TABLE feature_registry
    DROP CONSTRAINT IF EXISTS feature_registry_group_name_check;

ALTER TABLE feature_registry
    ADD CONSTRAINT feature_registry_group_name_check
    CHECK (group_name IN (
        'momentum', 'volume', 'volatility', 'structure',
        'session', 'oscillator', 'calendar', 'cross_tf',
        'macro', 'regime', 'control'
    ));

-- No tier CHECK change needed: canaries are single-column, fixed-window, so
-- tier='0_atomic' is already legal (migration 172's existing CHECK).

-- ---------------------------------------------------------------------------
-- 2. feature_vectors: 5 canary columns
-- ---------------------------------------------------------------------------

ALTER TABLE feature_vectors ADD COLUMN IF NOT EXISTS canary_noise_gaussian DOUBLE PRECISION;
ALTER TABLE feature_vectors ADD COLUMN IF NOT EXISTS canary_noise_uniform DOUBLE PRECISION;
ALTER TABLE feature_vectors ADD COLUMN IF NOT EXISTS canary_constant DOUBLE PRECISION;
ALTER TABLE feature_vectors ADD COLUMN IF NOT EXISTS canary_near_constant DOUBLE PRECISION;
ALTER TABLE feature_vectors ADD COLUMN IF NOT EXISTS canary_acausal_placebo DOUBLE PRECISION;

COMMENT ON COLUMN feature_vectors.canary_noise_gaussian IS
    'Seeded N(0,1) noise (APR: alpha.ic.canary_rng_seed). Negative control — must never '
    'carry IC. Phase 143.1 Plan 02, todo 068.';
COMMENT ON COLUMN feature_vectors.canary_noise_uniform IS
    'Seeded Uniform[0,1) noise, independent sub-seed of the same APR base key. Negative '
    'control — must never carry IC. Phase 143.1 Plan 02, todo 068.';
COMMENT ON COLUMN feature_vectors.canary_constant IS
    'Fixed literal (no APR — definitional degenerate-input control). Negative control. '
    'Phase 143.1 Plan 02, todo 068.';
COMMENT ON COLUMN feature_vectors.canary_near_constant IS
    'Literal plus tiny deterministic epsilon noise — verifies degenerate near-zero-'
    'variance handling. Negative control. Phase 143.1 Plan 02, todo 068.';
COMMENT ON COLUMN feature_vectors.canary_acausal_placebo IS
    'Existing feature deliberately paired against a forward-shifted return window '
    '(deliberate look-ahead leak). Positive control — must clear the IC significance '
    'gate spectacularly, proving this pipeline can detect contamination when genuinely '
    'present. Phase 143.1 Plan 02, todo 068.';

-- ---------------------------------------------------------------------------
-- 3. feature_registry seeding: 5 canary rows
-- ---------------------------------------------------------------------------

INSERT INTO feature_registry
    (feature_name, group_name, tier, formula_short, normalization, linear_ready,
     requires_htf, status, added_phase, is_control, control_expectation, notes)
VALUES
(
    'canary_noise_gaussian', 'control', '0_atomic', 'seeded N(0,1) draw',
    'unbounded_signed', true, false, 'candidate', '143.1',
    true, 'negative_control',
    'Pure Gaussian noise canary. Must never clear ic_ci_lower>0 AND passes_fdr in any '
    'stratum (POOLED hard-halt; per-symbol clears counted against a pre-committed '
    'Binomial bound — see ops_canary_integrity_assert.py).'
),
(
    'canary_noise_uniform', 'control', '0_atomic', 'seeded Uniform[0,1) draw',
    'bounded_unsigned', true, false, 'candidate', '143.1',
    true, 'negative_control',
    'Pure uniform noise canary, independently seeded from canary_noise_gaussian. Two '
    'distributionally-distinct null RNG sources agreeing is stronger integrity evidence '
    'than one alone. Same gate expectation as canary_noise_gaussian.'
),
(
    'canary_constant', 'control', '0_atomic', 'fixed literal 1.0',
    'unbounded_signed', false, false, 'candidate', '143.1',
    true, 'negative_control',
    'Degenerate constant-input canary. Zero variance by construction — verifies the '
    'pipeline does not spuriously assign significance to a non-varying input.'
),
(
    'canary_near_constant', 'control', '0_atomic', '1.0 + tiny deterministic epsilon noise',
    'unbounded_signed', false, false, 'candidate', '143.1',
    true, 'negative_control',
    'Near-degenerate canary (epsilon=1e-6 noise around the constant). Verifies '
    'degenerate near-zero-variance input handling distinctly from the pure constant.'
),
(
    'canary_acausal_placebo', 'control', '0_atomic',
    'existing feature paired against a forward-shifted (T+1->T+2) return window',
    'unbounded_ratio', false, false, 'candidate', '143.1',
    true, 'positive_control',
    'Deliberate look-ahead leak canary. Must clear ic_ci_lower>0 AND passes_fdr '
    'spectacularly in the POOLED stratum — the corpus-run assertion hard-halts if it '
    'does NOT clear, since that would mean the pipeline fails to detect genuine '
    'contamination when present.'
)
ON CONFLICT (feature_name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. APR key: alpha.ic.canary_rng_seed
-- ---------------------------------------------------------------------------

INSERT INTO config_schema (config_key, value_type, default_value, min_value, max_value, description)
VALUES
(
    'alpha.ic.canary_rng_seed',
    'int',
    '90042',
    0, 4294967295,
    '[initial_estimate] Base RNG seed for the canary_noise_gaussian/canary_noise_uniform '
    'control predictors (feature_factory.py._canary_sub_seed derives independent '
    'per-canary, per-bar sub-seeds from this one key). Changing it changes every canary '
    'noise value corpus-wide, invalidating any in-flight canary integrity comparison — '
    'same caution class as alpha.hmm.random_state. Not an ML learning target.'
)
ON CONFLICT (config_key) DO NOTHING;

INSERT INTO config_state (config_key, config_value, version)
VALUES ('alpha.ic.canary_rng_seed', '90042', 1)
ON CONFLICT (config_key) DO NOTHING;

INSERT INTO config_history (timestamp, config_key, version, config_value, changed_by, reason)
VALUES (
    NOW(), 'alpha.ic.canary_rng_seed', 1, '90042', 'migration_223',
    'Initial estimate: canary predictor RNG base seed [initial_estimate]'
)
ON CONFLICT DO NOTHING;

COMMIT;
