-- Migration 312: feature_vectors float64 -> float32 (real) storage type, drift fix
--
-- Migration 201 (2026-07-09) converted 156 double-precision feature columns to
-- real, with the rationale that every consumer already truncates these values
-- to float32 in memory immediately on read (services/ic_engine.py,
-- services/ensemble_trainer.py -- "rank-based IC doesn't need float64 raw
-- values") so storing float64 in the table added zero effective precision.
--
-- Every feature-column-adding migration SINCE 201 reverted to DOUBLE PRECISION
-- instead of following that convention (216 canary predictors, 255 VP/SR
-- structural primitives [Phase 163], 266 SMC institutional footprint [Phase
-- 164], 267 swing/fib/trend structure [Phase 165], 288-293 Phase 151 waves
-- 6-7 primitives, 307 regime-volatility). This migration extends 201's fix to
-- the 303 columns that drifted back to double precision -- same rationale,
-- same audit method (spot-checked column semantics: z-scores, ratios,
-- distances-in-ATR-units, trig encodings, probabilities, small bounded
-- counts, boolean flags -- none carry raw price levels or accumulator sums
-- that would need float8 range/precision).
--
-- Timed deliberately to run as part of the feature_vectors wipe-and-recompute
-- (todo 259 backfill completion -> Phase 151 waves 6-7 + regime rebuild):
-- run this AFTER truncating feature_vectors and BEFORE repopulating, so the
-- decompress/recompress dance below is a no-op on an empty table instead of
-- rewriting 48GB of live compressed data. If run against live data instead,
-- it is still correct -- just slower (mirrors 201's decompress-alter-
-- recompress pattern for that case).

BEGIN;

DO $$
DECLARE
  c record;
BEGIN
  FOR c IN
    SELECT format('%I.%I', chunk_schema, chunk_name)::regclass AS chunk
    FROM timescaledb_information.chunks
    WHERE hypertable_name = 'feature_vectors' AND is_compressed
  LOOP
    PERFORM decompress_chunk(c.chunk);
  END LOOP;
END $$;

ALTER TABLE feature_vectors
    ALTER COLUMN above_wk_vwap TYPE real USING above_wk_vwap::real,
    ALTER COLUMN abs_ret_autocorr_1 TYPE real USING abs_ret_autocorr_1::real,
    ALTER COLUMN active_demand_zones TYPE real USING active_demand_zones::real,
    ALTER COLUMN active_supply_zones TYPE real USING active_supply_zones::real,
    ALTER COLUMN adx TYPE real USING adx::real,
    ALTER COLUMN amd_distribution_direction TYPE real USING amd_distribution_direction::real,
    ALTER COLUMN amd_manipulation_detected TYPE real USING amd_manipulation_detected::real,
    ALTER COLUMN amd_phase TYPE real USING amd_phase::real,
    ALTER COLUMN amihud_illiq_z TYPE real USING amihud_illiq_z::real,
    ALTER COLUMN aroon_fast TYPE real USING aroon_fast::real,
    ALTER COLUMN aroon_slow TYPE real USING aroon_slow::real,
    ALTER COLUMN asian_session_high_dist_atr TYPE real USING asian_session_high_dist_atr::real,
    ALTER COLUMN asian_session_low_dist_atr TYPE real USING asian_session_low_dist_atr::real,
    ALTER COLUMN atr_z TYPE real USING atr_z::real,
    ALTER COLUMN bar_close_pos TYPE real USING bar_close_pos::real,
    ALTER COLUMN bars_since_52w_high TYPE real USING bars_since_52w_high::real,
    ALTER COLUMN bars_since_52w_low TYPE real USING bars_since_52w_low::real,
    ALTER COLUMN bars_since_extreme_move_fast TYPE real USING bars_since_extreme_move_fast::real,
    ALTER COLUMN bars_since_extreme_move_slow TYPE real USING bars_since_extreme_move_slow::real,
    ALTER COLUMN bars_since_high_fast TYPE real USING bars_since_high_fast::real,
    ALTER COLUMN bars_since_high_slow TYPE real USING bars_since_high_slow::real,
    ALTER COLUMN bars_since_last_shift TYPE real USING bars_since_last_shift::real,
    ALTER COLUMN bars_since_last_sweep TYPE real USING bars_since_last_sweep::real,
    ALTER COLUMN bars_since_low_fast TYPE real USING bars_since_low_fast::real,
    ALTER COLUMN bars_since_low_slow TYPE real USING bars_since_low_slow::real,
    ALTER COLUMN bars_since_vol_spike_fast TYPE real USING bars_since_vol_spike_fast::real,
    ALTER COLUMN bars_since_vol_spike_slow TYPE real USING bars_since_vol_spike_slow::real,
    ALTER COLUMN bb_pct_b_fast TYPE real USING bb_pct_b_fast::real,
    ALTER COLUMN bb_pct_b_slow TYPE real USING bb_pct_b_slow::real,
    ALTER COLUMN body_ratio TYPE real USING body_ratio::real,
    ALTER COLUMN bos_direction TYPE real USING bos_direction::real,
    ALTER COLUMN bos_strength TYPE real USING bos_strength::real,
    ALTER COLUMN breaker_block_active TYPE real USING breaker_block_active::real,
    ALTER COLUMN breaker_dist_atr TYPE real USING breaker_dist_atr::real,
    ALTER COLUMN breakout_volume_product TYPE real USING breakout_volume_product::real,
    ALTER COLUMN bsl_dist_atr TYPE real USING bsl_dist_atr::real,
    ALTER COLUMN bsl_touches TYPE real USING bsl_touches::real,
    ALTER COLUMN canary_acausal_placebo TYPE real USING canary_acausal_placebo::real,
    ALTER COLUMN canary_constant TYPE real USING canary_constant::real,
    ALTER COLUMN canary_near_constant TYPE real USING canary_near_constant::real,
    ALTER COLUMN canary_noise_gaussian TYPE real USING canary_noise_gaussian::real,
    ALTER COLUMN canary_noise_uniform TYPE real USING canary_noise_uniform::real,
    ALTER COLUMN cci_fast TYPE real USING cci_fast::real,
    ALTER COLUMN cci_mid TYPE real USING cci_mid::real,
    ALTER COLUMN cci_slow TYPE real USING cci_slow::real,
    ALTER COLUMN choch_direction TYPE real USING choch_direction::real,
    ALTER COLUMN choch_strength TYPE real USING choch_strength::real,
    ALTER COLUMN close_vs_open_direction TYPE real USING close_vs_open_direction::real,
    ALTER COLUMN cmf TYPE real USING cmf::real,
    ALTER COLUMN ctf_momentum TYPE real USING ctf_momentum::real,
    ALTER COLUMN ctf_regime_align TYPE real USING ctf_regime_align::real,
    ALTER COLUMN ctf_vwap_align TYPE real USING ctf_vwap_align::real,
    ALTER COLUMN cvd_slope_z TYPE real USING cvd_slope_z::real,
    ALTER COLUMN day_of_month_cos TYPE real USING day_of_month_cos::real,
    ALTER COLUMN day_of_month_sin TYPE real USING day_of_month_sin::real,
    ALTER COLUMN days_to_month_end TYPE real USING days_to_month_end::real,
    ALTER COLUMN demand_dist_atr TYPE real USING demand_dist_atr::real,
    ALTER COLUMN demand_freshness TYPE real USING demand_freshness::real,
    ALTER COLUMN dist_from_high_fast TYPE real USING dist_from_high_fast::real,
    ALTER COLUMN dist_from_high_slow TYPE real USING dist_from_high_slow::real,
    ALTER COLUMN dist_from_low_fast TYPE real USING dist_from_low_fast::real,
    ALTER COLUMN dist_from_low_slow TYPE real USING dist_from_low_slow::real,
    ALTER COLUMN distance_to_vah_atr TYPE real USING distance_to_vah_atr::real,
    ALTER COLUMN distance_to_val_atr TYPE real USING distance_to_val_atr::real,
    ALTER COLUMN dollar_vol_z TYPE real USING dollar_vol_z::real,
    ALTER COLUMN dow_cos TYPE real USING dow_cos::real,
    ALTER COLUMN dow_sin TYPE real USING dow_sin::real,
    ALTER COLUMN efficiency_ratio_fast TYPE real USING efficiency_ratio_fast::real,
    ALTER COLUMN efficiency_ratio_slow TYPE real USING efficiency_ratio_slow::real,
    ALTER COLUMN efficiency_volume_product TYPE real USING efficiency_volume_product::real,
    ALTER COLUMN equity_beta_z TYPE real USING equity_beta_z::real,
    ALTER COLUMN fib_cluster_strength TYPE real USING fib_cluster_strength::real,
    ALTER COLUMN flight_quality TYPE real USING flight_quality::real,
    ALTER COLUMN fvg_dist_atr TYPE real USING fvg_dist_atr::real,
    ALTER COLUMN fvg_open_count TYPE real USING fvg_open_count::real,
    ALTER COLUMN fvg_size_atr TYPE real USING fvg_size_atr::real,
    ALTER COLUMN gap_filled TYPE real USING gap_filled::real,
    ALTER COLUMN gap_z TYPE real USING gap_z::real,
    ALTER COLUMN garch_ratio TYPE real USING garch_ratio::real,
    ALTER COLUMN garman_klass_vol_velocity TYPE real USING garman_klass_vol_velocity::real,
    ALTER COLUMN garman_klass_vol_z TYPE real USING garman_klass_vol_z::real,
    ALTER COLUMN high_52w_dist TYPE real USING high_52w_dist::real,
    ALTER COLUMN high_low_corr TYPE real USING high_low_corr::real,
    ALTER COLUMN hma_slope_z TYPE real USING hma_slope_z::real,
    ALTER COLUMN hmm_churn TYPE real USING hmm_churn::real,
    ALTER COLUMN hmm_duration TYPE real USING hmm_duration::real,
    ALTER COLUMN hmm_entropy TYPE real USING hmm_entropy::real,
    ALTER COLUMN hmm_prob_ranging TYPE real USING hmm_prob_ranging::real,
    ALTER COLUMN hmm_prob_trending_down TYPE real USING hmm_prob_trending_down::real,
    ALTER COLUMN hmm_prob_trending_up TYPE real USING hmm_prob_trending_up::real,
    ALTER COLUMN hmm_regime_prob TYPE real USING hmm_regime_prob::real,
    ALTER COLUMN hmm_vol_churn TYPE real USING hmm_vol_churn::real,
    ALTER COLUMN hmm_vol_duration TYPE real USING hmm_vol_duration::real,
    ALTER COLUMN hmm_vol_entropy TYPE real USING hmm_vol_entropy::real,
    ALTER COLUMN hmm_vol_prob_calm TYPE real USING hmm_vol_prob_calm::real,
    ALTER COLUMN hmm_vol_prob_elevated TYPE real USING hmm_vol_prob_elevated::real,
    ALTER COLUMN hmm_vol_prob_turbulent TYPE real USING hmm_vol_prob_turbulent::real,
    ALTER COLUMN hmm_vol_regime_prob TYPE real USING hmm_vol_regime_prob::real,
    ALTER COLUMN hour_of_day_cos TYPE real USING hour_of_day_cos::real,
    ALTER COLUMN hour_of_day_sin TYPE real USING hour_of_day_sin::real,
    ALTER COLUMN hurst TYPE real USING hurst::real,
    ALTER COLUMN hv_ratio TYPE real USING hv_ratio::real,
    ALTER COLUMN hv_z_fast TYPE real USING hv_z_fast::real,
    ALTER COLUMN hv_z_slow TYPE real USING hv_z_slow::real,
    ALTER COLUMN hyg_lqd_ret_z TYPE real USING hyg_lqd_ret_z::real,
    ALTER COLUMN illiquidity_momentum_product TYPE real USING illiquidity_momentum_product::real,
    ALTER COLUMN in_fib_discount_zone TYPE real USING in_fib_discount_zone::real,
    ALTER COLUMN in_london_kz TYPE real USING in_london_kz::real,
    ALTER COLUMN in_lvn TYPE real USING in_lvn::real,
    ALTER COLUMN in_ny_session TYPE real USING in_ny_session::real,
    ALTER COLUMN in_overlap TYPE real USING in_overlap::real,
    ALTER COLUMN informed_flow TYPE real USING informed_flow::real,
    ALTER COLUMN intraday_noise_ratio TYPE real USING intraday_noise_ratio::real,
    ALTER COLUMN intraday_ret TYPE real USING intraday_ret::real,
    ALTER COLUMN lower_wick_ratio TYPE real USING lower_wick_ratio::real,
    ALTER COLUMN manip_strength TYPE real USING manip_strength::real,
    ALTER COLUMN mfi_fast TYPE real USING mfi_fast::real,
    ALTER COLUMN mfi_slow TYPE real USING mfi_slow::real,
    ALTER COLUMN minute_of_hour_cos TYPE real USING minute_of_hour_cos::real,
    ALTER COLUMN minute_of_hour_sin TYPE real USING minute_of_hour_sin::real,
    ALTER COLUMN momentum_rank_z TYPE real USING momentum_rank_z::real,
    ALTER COLUMN momentum_reversal_z TYPE real USING momentum_reversal_z::real,
    ALTER COLUMN momentum_trend_product TYPE real USING momentum_trend_product::real,
    ALTER COLUMN momentum_vol_regime_product TYPE real USING momentum_vol_regime_product::real,
    ALTER COLUMN momentum_z_fast TYPE real USING momentum_z_fast::real,
    ALTER COLUMN momentum_z_mid TYPE real USING momentum_z_mid::real,
    ALTER COLUMN momentum_z_slow TYPE real USING momentum_z_slow::real,
    ALTER COLUMN momentum_z_velocity_fast TYPE real USING momentum_z_velocity_fast::real,
    ALTER COLUMN momentum_z_velocity_mid TYPE real USING momentum_z_velocity_mid::real,
    ALTER COLUMN momentum_z_velocity_slow TYPE real USING momentum_z_velocity_slow::real,
    ALTER COLUMN month_cos TYPE real USING month_cos::real,
    ALTER COLUMN month_position TYPE real USING month_position::real,
    ALTER COLUMN month_sin TYPE real USING month_sin::real,
    ALTER COLUMN nearest_fib_dist_atr TYPE real USING nearest_fib_dist_atr::real,
    ALTER COLUMN nearest_fib_ratio TYPE real USING nearest_fib_ratio::real,
    ALTER COLUMN nearest_hvn_above_dist_atr TYPE real USING nearest_hvn_above_dist_atr::real,
    ALTER COLUMN nearest_hvn_below_dist_atr TYPE real USING nearest_hvn_below_dist_atr::real,
    ALTER COLUMN nearest_hvn_dist_atr TYPE real USING nearest_hvn_dist_atr::real,
    ALTER COLUMN nearest_level_dist_atr TYPE real USING nearest_level_dist_atr::real,
    ALTER COLUMN nearest_lvn_above_dist_atr TYPE real USING nearest_lvn_above_dist_atr::real,
    ALTER COLUMN nearest_lvn_below_dist_atr TYPE real USING nearest_lvn_below_dist_atr::real,
    ALTER COLUMN ob_bear_dist_atr TYPE real USING ob_bear_dist_atr::real,
    ALTER COLUMN ob_bull_dist_atr TYPE real USING ob_bull_dist_atr::real,
    ALTER COLUMN ob_mitigated_flag TYPE real USING ob_mitigated_flag::real,
    ALTER COLUMN ob_mitigation_pct TYPE real USING ob_mitigation_pct::real,
    ALTER COLUMN ob_strength TYPE real USING ob_strength::real,
    ALTER COLUMN obv_z TYPE real USING obv_z::real,
    ALTER COLUMN ofi_div TYPE real USING ofi_div::real,
    ALTER COLUMN ofi_z TYPE real USING ofi_z::real,
    ALTER COLUMN open_ret TYPE real USING open_ret::real,
    ALTER COLUMN open_vs_intraday TYPE real USING open_vs_intraday::real,
    ALTER COLUMN opening_gap_pct TYPE real USING opening_gap_pct::real,
    ALTER COLUMN opening_range TYPE real USING opening_range::real,
    ALTER COLUMN opex_flag TYPE real USING opex_flag::real,
    ALTER COLUMN overnight_gap TYPE real USING overnight_gap::real,
    ALTER COLUMN overnight_gap_z TYPE real USING overnight_gap_z::real,
    ALTER COLUMN overnight_high_dist_atr TYPE real USING overnight_high_dist_atr::real,
    ALTER COLUMN overnight_low_dist_atr TYPE real USING overnight_low_dist_atr::real,
    ALTER COLUMN overnight_range_pct TYPE real USING overnight_range_pct::real,
    ALTER COLUMN parkinson_vol_velocity TYPE real USING parkinson_vol_velocity::real,
    ALTER COLUMN parkinson_vol_z TYPE real USING parkinson_vol_z::real,
    ALTER COLUMN poc_dist_atr TYPE real USING poc_dist_atr::real,
    ALTER COLUMN poc_rolling_dist_atr TYPE real USING poc_rolling_dist_atr::real,
    ALTER COLUMN poc_session_rolling_divergence_atr TYPE real USING poc_session_rolling_divergence_atr::real,
    ALTER COLUMN pool_count TYPE real USING pool_count::real,
    ALTER COLUMN power_hour TYPE real USING power_hour::real,
    ALTER COLUMN price_in_value_area TYPE real USING price_in_value_area::real,
    ALTER COLUMN price_percentile_fast TYPE real USING price_percentile_fast::real,
    ALTER COLUMN price_percentile_slow TYPE real USING price_percentile_slow::real,
    ALTER COLUMN price_position TYPE real USING price_position::real,
    ALTER COLUMN price_vol_corr_fast TYPE real USING price_vol_corr_fast::real,
    ALTER COLUMN price_vol_corr_slow TYPE real USING price_vol_corr_slow::real,
    ALTER COLUMN prior_session_close_dist_atr TYPE real USING prior_session_close_dist_atr::real,
    ALTER COLUMN prior_session_high_dist_atr TYPE real USING prior_session_high_dist_atr::real,
    ALTER COLUMN prior_session_low_dist_atr TYPE real USING prior_session_low_dist_atr::real,
    ALTER COLUMN quad_witching_flag TYPE real USING quad_witching_flag::real,
    ALTER COLUMN quarter_cycle_cos TYPE real USING quarter_cycle_cos::real,
    ALTER COLUMN quarter_cycle_sin TYPE real USING quarter_cycle_sin::real,
    ALTER COLUMN quarter_momentum_product TYPE real USING quarter_momentum_product::real,
    ALTER COLUMN quarter_position TYPE real USING quarter_position::real,
    ALTER COLUMN range_efficiency TYPE real USING range_efficiency::real,
    ALTER COLUMN range_pct_fast TYPE real USING range_pct_fast::real,
    ALTER COLUMN range_pct_slow TYPE real USING range_pct_slow::real,
    ALTER COLUMN range_position TYPE real USING range_position::real,
    ALTER COLUMN range_to_close TYPE real USING range_to_close::real,
    ALTER COLUMN range_vol_product TYPE real USING range_vol_product::real,
    ALTER COLUMN range_vs_atr TYPE real USING range_vs_atr::real,
    ALTER COLUMN rate_beta_z TYPE real USING rate_beta_z::real,
    ALTER COLUMN realized_var_ratio_fast TYPE real USING realized_var_ratio_fast::real,
    ALTER COLUMN realized_var_ratio_slow TYPE real USING realized_var_ratio_slow::real,
    ALTER COLUMN reclaim_velocity TYPE real USING reclaim_velocity::real,
    ALTER COLUMN rel_volume TYPE real USING rel_volume::real,
    ALTER COLUMN resistance_age_bars TYPE real USING resistance_age_bars::real,
    ALTER COLUMN resistance_strength TYPE real USING resistance_strength::real,
    ALTER COLUMN ret_acf1_z TYPE real USING ret_acf1_z::real,
    ALTER COLUMN ret_autocorr_1 TYPE real USING ret_autocorr_1::real,
    ALTER COLUMN ret_autocorr_5 TYPE real USING ret_autocorr_5::real,
    ALTER COLUMN ret_div_1h_1d TYPE real USING ret_div_1h_1d::real,
    ALTER COLUMN ret_div_1m_5m TYPE real USING ret_div_1m_5m::real,
    ALTER COLUMN ret_div_5m_1h TYPE real USING ret_div_5m_1h::real,
    ALTER COLUMN ret_kurtosis_z_fast TYPE real USING ret_kurtosis_z_fast::real,
    ALTER COLUMN ret_kurtosis_z_slow TYPE real USING ret_kurtosis_z_slow::real,
    ALTER COLUMN ret_lag_1 TYPE real USING ret_lag_1::real,
    ALTER COLUMN ret_lag_2 TYPE real USING ret_lag_2::real,
    ALTER COLUMN ret_lag_3 TYPE real USING ret_lag_3::real,
    ALTER COLUMN ret_lag_fast TYPE real USING ret_lag_fast::real,
    ALTER COLUMN ret_lag_mid TYPE real USING ret_lag_mid::real,
    ALTER COLUMN ret_lag_slow TYPE real USING ret_lag_slow::real,
    ALTER COLUMN ret_skew_z TYPE real USING ret_skew_z::real,
    ALTER COLUMN ret_vol_product_fast TYPE real USING ret_vol_product_fast::real,
    ALTER COLUMN ret_vol_ratio_fast TYPE real USING ret_vol_ratio_fast::real,
    ALTER COLUMN reversion_hurst_product TYPE real USING reversion_hurst_product::real,
    ALTER COLUMN rsi_fast TYPE real USING rsi_fast::real,
    ALTER COLUMN rsi_mid TYPE real USING rsi_mid::real,
    ALTER COLUMN rsi_slow TYPE real USING rsi_slow::real,
    ALTER COLUMN sb_corr_fast TYPE real USING sb_corr_fast::real,
    ALTER COLUMN sb_corr_slow TYPE real USING sb_corr_slow::real,
    ALTER COLUMN sb_corr_z TYPE real USING sb_corr_z::real,
    ALTER COLUMN session_time_pos TYPE real USING session_time_pos::real,
    ALTER COLUMN shannon TYPE real USING shannon::real,
    ALTER COLUMN smc_trend_direction TYPE real USING smc_trend_direction::real,
    ALTER COLUMN sr_level_count TYPE real USING sr_level_count::real,
    ALTER COLUMN sr_resist_dist TYPE real USING sr_resist_dist::real,
    ALTER COLUMN sr_support_dist TYPE real USING sr_support_dist::real,
    ALTER COLUMN ssl_dist_atr TYPE real USING ssl_dist_atr::real,
    ALTER COLUMN ssl_touches TYPE real USING ssl_touches::real,
    ALTER COLUMN stoch_k_fast TYPE real USING stoch_k_fast::real,
    ALTER COLUMN stoch_k_slow TYPE real USING stoch_k_slow::real,
    ALTER COLUMN streak_z TYPE real USING streak_z::real,
    ALTER COLUMN struct_accel_bias TYPE real USING struct_accel_bias::real,
    ALTER COLUMN struct_energy TYPE real USING struct_energy::real,
    ALTER COLUMN structure_integrity TYPE real USING structure_integrity::real,
    ALTER COLUMN supply_dist_atr TYPE real USING supply_dist_atr::real,
    ALTER COLUMN supply_freshness TYPE real USING supply_freshness::real,
    ALTER COLUMN support_age_bars TYPE real USING support_age_bars::real,
    ALTER COLUMN support_strength TYPE real USING support_strength::real,
    ALTER COLUMN sweep_detected TYPE real USING sweep_detected::real,
    ALTER COLUMN sweep_strength TYPE real USING sweep_strength::real,
    ALTER COLUMN swing_amplitude_expanding TYPE real USING swing_amplitude_expanding::real,
    ALTER COLUMN swing_amplitude_intensity TYPE real USING swing_amplitude_intensity::real,
    ALTER COLUMN swing_amplitude_ratio TYPE real USING swing_amplitude_ratio::real,
    ALTER COLUMN swing_high_age_bars TYPE real USING swing_high_age_bars::real,
    ALTER COLUMN swing_high_dist_atr TYPE real USING swing_high_dist_atr::real,
    ALTER COLUMN swing_high_type TYPE real USING swing_high_type::real,
    ALTER COLUMN swing_low_age_bars TYPE real USING swing_low_age_bars::real,
    ALTER COLUMN swing_low_dist_atr TYPE real USING swing_low_dist_atr::real,
    ALTER COLUMN swing_low_type TYPE real USING swing_low_type::real,
    ALTER COLUMN swing_pattern TYPE real USING swing_pattern::real,
    ALTER COLUMN swing_velocity_bars TYPE real USING swing_velocity_bars::real,
    ALTER COLUMN swing_velocity_bias TYPE real USING swing_velocity_bias::real,
    ALTER COLUMN swing_volume_confirmation TYPE real USING swing_volume_confirmation::real,
    ALTER COLUMN tdom_cos TYPE real USING tdom_cos::real,
    ALTER COLUMN tdom_sin TYPE real USING tdom_sin::real,
    ALTER COLUMN tip_tlt_ret_z TYPE real USING tip_tlt_ret_z::real,
    ALTER COLUMN trend_direction TYPE real USING trend_direction::real,
    ALTER COLUMN trend_duration_bars TYPE real USING trend_duration_bars::real,
    ALTER COLUMN trend_leg_count TYPE real USING trend_leg_count::real,
    ALTER COLUMN trend_strength TYPE real USING trend_strength::real,
    ALTER COLUMN true_range_pct TYPE real USING true_range_pct::real,
    ALTER COLUMN up_vol_body_diff TYPE real USING up_vol_body_diff::real,
    ALTER COLUMN up_vol_ratio_fast TYPE real USING up_vol_ratio_fast::real,
    ALTER COLUMN up_vol_ratio_slow TYPE real USING up_vol_ratio_slow::real,
    ALTER COLUMN updown_ratio_fast TYPE real USING updown_ratio_fast::real,
    ALTER COLUMN updown_ratio_slow TYPE real USING updown_ratio_slow::real,
    ALTER COLUMN upper_wick_ratio TYPE real USING upper_wick_ratio::real,
    ALTER COLUMN va_position TYPE real USING va_position::real,
    ALTER COLUMN va_width_atr TYPE real USING va_width_atr::real,
    ALTER COLUMN variance_ratio_fast TYPE real USING variance_ratio_fast::real,
    ALTER COLUMN variance_ratio_momentum_product TYPE real USING variance_ratio_momentum_product::real,
    ALTER COLUMN variance_ratio_slow TYPE real USING variance_ratio_slow::real,
    ALTER COLUMN vix_reversion_product TYPE real USING vix_reversion_product::real,
    ALTER COLUMN vix_z TYPE real USING vix_z::real,
    ALTER COLUMN vol_acceleration TYPE real USING vol_acceleration::real,
    ALTER COLUMN vol_asymmetry_z TYPE real USING vol_asymmetry_z::real,
    ALTER COLUMN vol_body_product TYPE real USING vol_body_product::real,
    ALTER COLUMN vol_of_vol TYPE real USING vol_of_vol::real,
    ALTER COLUMN vol_percentile TYPE real USING vol_percentile::real,
    ALTER COLUMN vol_persistence TYPE real USING vol_persistence::real,
    ALTER COLUMN vol_range_ratio TYPE real USING vol_range_ratio::real,
    ALTER COLUMN vol_ratio TYPE real USING vol_ratio::real,
    ALTER COLUMN vol_skew_product TYPE real USING vol_skew_product::real,
    ALTER COLUMN vol_std_z TYPE real USING vol_std_z::real,
    ALTER COLUMN vol_trend_ratio TYPE real USING vol_trend_ratio::real,
    ALTER COLUMN vol_velocity_z TYPE real USING vol_velocity_z::real,
    ALTER COLUMN volatility_rank_z TYPE real USING volatility_rank_z::real,
    ALTER COLUMN volume_rank_z TYPE real USING volume_rank_z::real,
    ALTER COLUMN volume_z TYPE real USING volume_z::real,
    ALTER COLUMN vwap_dev_sigma TYPE real USING vwap_dev_sigma::real,
    ALTER COLUMN vwap_dev_sigma_velocity TYPE real USING vwap_dev_sigma_velocity::real,
    ALTER COLUMN week_of_month_cos TYPE real USING week_of_month_cos::real,
    ALTER COLUMN week_of_month_sin TYPE real USING week_of_month_sin::real,
    ALTER COLUMN week_of_year_cos TYPE real USING week_of_year_cos::real,
    ALTER COLUMN week_of_year_sin TYPE real USING week_of_year_sin::real,
    ALTER COLUMN weekly_pivot_dist_atr TYPE real USING weekly_pivot_dist_atr::real,
    ALTER COLUMN weekly_r1_dist_atr TYPE real USING weekly_r1_dist_atr::real,
    ALTER COLUMN weekly_r2_dist_atr TYPE real USING weekly_r2_dist_atr::real,
    ALTER COLUMN weekly_s1_dist_atr TYPE real USING weekly_s1_dist_atr::real,
    ALTER COLUMN weekly_s2_dist_atr TYPE real USING weekly_s2_dist_atr::real,
    ALTER COLUMN yang_zhang_vol_velocity TYPE real USING yang_zhang_vol_velocity::real,
    ALTER COLUMN yang_zhang_vol_z TYPE real USING yang_zhang_vol_z::real,
    ALTER COLUMN yield_slope_momentum_product TYPE real USING yield_slope_momentum_product::real,
    ALTER COLUMN yield_slope_z TYPE real USING yield_slope_z::real,
    ALTER COLUMN zone_friction_score TYPE real USING zone_friction_score::real;

COMMIT;

-- Recompression is intentionally a separate statement (outside the DDL
-- transaction), same reasoning as migration 201: compress_chunk() takes its
-- own per-chunk locks and this way a failure partway through recompression
-- can't roll back the (already-verified) type change.
DO $$
DECLARE
  c record;
BEGIN
  FOR c IN
    SELECT format('%I.%I', chunk_schema, chunk_name)::regclass AS chunk
    FROM timescaledb_information.chunks
    WHERE hypertable_name = 'feature_vectors' AND NOT is_compressed
  LOOP
    PERFORM compress_chunk(c.chunk);
  END LOOP;
END $$;
