-- Migration 380: D1, the raw observation store for 1d bars (phase 185 plan 02, D-05)
--
-- D1 holds the raw IBKR answers that every later derivation audits. ohlcv_request logs
-- each history request and its outcome (bars, no_data, timeout, failed, legacy_import)
-- for any timeframe, because D4's intraday re-verification needs those outcomes;
-- ohlcv_observation holds every 1d bar answered, per route and what_to_show (1d only:
-- intraday raw storage is deferred, D-02). Readers use canonical bars in
-- market_data_ohlcv; D1 is for derivation and audit. Both tables are permanent (raw
-- data is never rewritten, design section 12): UPDATE, DELETE and TRUNCATE raise for
-- every role, superuser included.
--
-- Plain tables, not hypertables: the projected size is 12-18M rows plus about 9M a
-- year (RESEARCH "Alternatives considered"), which a plain table serves fine; D1 is
-- appended per request and read per (symbol, route), not per time range. Revisit near
-- 50M rows.
--
-- The two writer roles are NOLOGIN and hold no credentials: the postgres login
-- narrows itself with SET LOCAL ROLE inside each write transaction (design 14.5), so
-- grants, not passwords, are the fence. source is a CHECKed column whose only value
-- today is 'ibkr'; adding a vendor is one CHECK change, no schema rebuild (D-01).

BEGIN;

CREATE TABLE IF NOT EXISTS ohlcv_request (
    request_id uuid PRIMARY KEY,
    fetch_run_id uuid NOT NULL,
    symbol text NOT NULL REFERENCES instruments(symbol) ON DELETE RESTRICT,
    timeframe text NOT NULL,
    source text NOT NULL CHECK (source IN ('ibkr')),
    route text NOT NULL CHECK (route ~ '^[A-Z_]{2,16}$'),
    what_to_show text NOT NULL CHECK (what_to_show IN ('TRADES', 'ADJUSTED_LAST')),
    primary_exchange text,
    window_start timestamptz,
    window_end timestamptz NOT NULL,
    ib_req_id integer,
    outcome text NOT NULL CHECK (outcome IN ('bars', 'no_data', 'timeout', 'failed', 'legacy_import')),
    error_code integer,
    error_text text,
    n_bars integer NOT NULL CHECK (n_bars >= 0),
    client_id integer,
    caller text NOT NULL,
    requested_at timestamptz NOT NULL,
    answered_at timestamptz NOT NULL
);

COMMENT ON TABLE ohlcv_request IS
    'Append-only log of every IBKR history request and its outcome (migration 380, D1). '
    'One row per request, any timeframe; request_id is generated by the provider. '
    'TRADES and ADJUSTED_LAST pair only within one fetch_run_id. Permanent: UPDATE, '
    'DELETE and TRUNCATE raise.';

CREATE TABLE IF NOT EXISTS ohlcv_observation (
    request_id uuid NOT NULL REFERENCES ohlcv_request(request_id) ON DELETE RESTRICT,
    symbol text NOT NULL,
    timeframe text NOT NULL CHECK (timeframe = '1d'),
    bar_date date NOT NULL,
    open double precision NOT NULL,
    high double precision NOT NULL,
    low double precision NOT NULL,
    close double precision NOT NULL,
    volume bigint,
    source text NOT NULL,
    route text NOT NULL,
    what_to_show text NOT NULL,
    fetched_at timestamptz NOT NULL,
    PRIMARY KEY (request_id, bar_date),
    -- NaN compares unequal to everything and Infinity passes <> comparisons, so
    -- explicit finite checks are required (same shape as dividend_events_finite).
    CONSTRAINT ohlcv_observation_finite CHECK (
        open <> 'NaN' AND open <> 'Infinity' AND open <> '-Infinity'
        AND high <> 'NaN' AND high <> 'Infinity' AND high <> '-Infinity'
        AND low <> 'NaN' AND low <> 'Infinity' AND low <> '-Infinity'
        AND close <> 'NaN' AND close <> 'Infinity' AND close <> '-Infinity'
    )
);

COMMENT ON TABLE ohlcv_observation IS
    'Append-only raw 1d bars as answered, one row per (request, bar_date), denormalized '
    'source/route/what_to_show from the request (migration 380, D1). 1d only (D-02). '
    'Permanent: UPDATE, DELETE and TRUNCATE raise. Readers use canonical bars in '
    'market_data_ohlcv; this table is for derivation and audit.';

CREATE INDEX IF NOT EXISTS idx_ohlcv_request_symbol_answered
    ON ohlcv_request (symbol, timeframe, route, what_to_show, answered_at DESC);

CREATE INDEX IF NOT EXISTS idx_ohlcv_request_fetch_run
    ON ohlcv_request (fetch_run_id);

CREATE INDEX IF NOT EXISTS idx_ohlcv_observation_symbol_date
    ON ohlcv_observation (symbol, bar_date, route, what_to_show, fetched_at DESC);

-- ---------------------------------------------------------------------------
-- Append-only: one function, four triggers (row UPDATE/DELETE + statement
-- TRUNCATE per table), each preceded by DROP TRIGGER IF EXISTS.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION ohlcv_d1_append_only()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'check_violation';
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION ohlcv_d1_append_only() IS
    'Refuses UPDATE, DELETE (row triggers) and TRUNCATE (statement triggers) on the D1 '
    'tables ohlcv_request and ohlcv_observation (migration 380): raw answers are '
    'permanent, an answer that was seen cannot be unseen.';

DROP TRIGGER IF EXISTS trg_ohlcv_request_append_only ON ohlcv_request;

CREATE TRIGGER trg_ohlcv_request_append_only
    BEFORE UPDATE OR DELETE ON ohlcv_request
    FOR EACH ROW
    EXECUTE FUNCTION ohlcv_d1_append_only();

DROP TRIGGER IF EXISTS trg_ohlcv_request_no_truncate ON ohlcv_request;

CREATE TRIGGER trg_ohlcv_request_no_truncate
    BEFORE TRUNCATE ON ohlcv_request
    FOR EACH STATEMENT
    EXECUTE FUNCTION ohlcv_d1_append_only();

DROP TRIGGER IF EXISTS trg_ohlcv_observation_append_only ON ohlcv_observation;

CREATE TRIGGER trg_ohlcv_observation_append_only
    BEFORE UPDATE OR DELETE ON ohlcv_observation
    FOR EACH ROW
    EXECUTE FUNCTION ohlcv_d1_append_only();

DROP TRIGGER IF EXISTS trg_ohlcv_observation_no_truncate ON ohlcv_observation;

CREATE TRIGGER trg_ohlcv_observation_no_truncate
    BEFORE TRUNCATE ON ohlcv_observation
    FOR EACH STATEMENT
    EXECUTE FUNCTION ohlcv_d1_append_only();

-- ---------------------------------------------------------------------------
-- Writer roles (NOLOGIN, reached through SET LOCAL ROLE by the postgres login)
-- ---------------------------------------------------------------------------

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ohlcv_observation_writer') THEN
        CREATE ROLE ohlcv_observation_writer NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bar_derivation_writer') THEN
        CREATE ROLE bar_derivation_writer NOLOGIN;
    END IF;
END
$$;

GRANT INSERT, SELECT ON ohlcv_request, ohlcv_observation TO ohlcv_observation_writer;
GRANT SELECT ON instruments TO ohlcv_observation_writer;
GRANT SELECT ON ohlcv_request, ohlcv_observation TO bar_derivation_writer;
REVOKE UPDATE, DELETE, TRUNCATE ON ohlcv_request, ohlcv_observation FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- Moved-name inventory: per non-SMART route, the head dates and whether the
-- route ends before the SMART head (D-20 evidence, D-25 input).
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW ohlcv_venue_head AS
WITH smart_head AS (
    SELECT symbol, min(bar_date) AS smart_head_date
    FROM ohlcv_observation
    WHERE route = 'SMART' AND what_to_show = 'TRADES'
    GROUP BY symbol
)
SELECT
    o.symbol,
    o.route,
    min(o.bar_date) AS first_bar_date,
    max(o.bar_date) AS last_bar_date,
    count(*) AS n_bars,
    sh.smart_head_date,
    (max(o.bar_date) < sh.smart_head_date OR sh.smart_head_date IS NULL) AS pre_move
FROM ohlcv_observation o
LEFT JOIN smart_head sh ON sh.symbol = o.symbol
WHERE o.route <> 'SMART'
  AND o.route <> 'LEGACY_IMPORT'
  AND o.what_to_show = 'TRADES'
GROUP BY o.symbol, o.route, sh.smart_head_date;

COMMENT ON VIEW ohlcv_venue_head IS
    'Per (symbol, non-SMART route): first and last TRADES 1d bar date, observation '
    'count, the symbol''s SMART TRADES head date (NULL if none), and pre_move = the '
    'route ends before the SMART head or there is no SMART head. The moved-name '
    'inventory (D-20 evidence, D-25 input).';

-- ---------------------------------------------------------------------------
-- APR seeds (infra.*): campaign client ids, history-lease waits, COPY batch size
-- ---------------------------------------------------------------------------

INSERT INTO config_schema (config_key, value_type, default_value, min_value, max_value, description) VALUES
    (
        'infra.bar_campaign.client_ids',
        'json',
        '[47, 48, 49]',
        NULL, NULL,
        '[initial_estimate] IBKR client ids reserved for phase 185 bar campaigns (D-30). 46 and 40 belong to the todo 449 chain and 45 to the nightly backfill, so campaign code must not take them; ids must stay <= 50 (the provider ceiling). Changing this only affects runs started afterwards. Not an ML learning target.'
    ),
    (
        'infra.ibkr_history_lease.nightly_wait_minutes',
        'int',
        '60',
        '1', '1440',
        '[initial_estimate] Minutes the nightly 1d backfill waits for the IBKR history-stream lease before failing loudly (D-29). A bulk-tier holder yields within one (symbol, tf) unit, about 18 minutes worst case, so 60 minutes covers a full yield cycle. Not an ML learning target.'
    ),
    (
        'infra.ibkr_history_lease.priority_wait_minutes',
        'int',
        '240',
        '1', '1440',
        '[initial_estimate] Minutes a priority-tier campaign waits for the IBKR history-stream lease before failing loudly (D-29). Longer than the nightly wait because a priority campaign is rarer and restarts are more expensive. Not an ML learning target.'
    ),
    (
        'infra.ohlcv_observation.copy_batch_rows',
        'int',
        '50000',
        '1000', '1000000',
        '[initial_estimate] Buffer size in rows at which the ohlcv_observation COPY writer flushes D1 requests and observations (phase 185 plan 02). Bounded to keep the in-memory buffer small against long campaigns. Not an ML learning target.'
    )
ON CONFLICT (config_key) DO NOTHING;

INSERT INTO config_state (config_key, config_value, version)
VALUES
    ('infra.bar_campaign.client_ids', '[47, 48, 49]', 1),
    ('infra.ibkr_history_lease.nightly_wait_minutes', '60', 1),
    ('infra.ibkr_history_lease.priority_wait_minutes', '240', 1),
    ('infra.ohlcv_observation.copy_batch_rows', '50000', 1)
ON CONFLICT (config_key) DO NOTHING;

INSERT INTO config_history (timestamp, config_key, version, config_value, changed_by, reason)
VALUES
    (NOW(), 'infra.bar_campaign.client_ids', 1, '[47, 48, 49]', 'migration_380', 'Initial value [initial_estimate]'),
    (NOW(), 'infra.ibkr_history_lease.nightly_wait_minutes', 1, '60', 'migration_380', 'Initial value [initial_estimate]'),
    (NOW(), 'infra.ibkr_history_lease.priority_wait_minutes', 1, '240', 'migration_380', 'Initial value [initial_estimate]'),
    (NOW(), 'infra.ohlcv_observation.copy_batch_rows', 1, '50000', 'migration_380', 'Initial value [initial_estimate]')
ON CONFLICT DO NOTHING;

COMMIT;
