-- Migration 425: feature_vectors_v2, the rebuilt append-only feature table (phase 186-24,
-- design 14.2 and 14.7, D-34, D-37, D-16).
--
-- Sole writer: services/_batch_utils.py bulk_load on behalf of the 186-25 rebuild writer.
-- The table is renamed onto feature_vectors at the 186-27 swap and the old table is dropped
-- there. No rows are written by this migration.
--
-- Columns: keys (symbol, tf, bar_ts), the two regime text columns, then every numeric column
-- of the kernel registry (feature_columns() order) minus the dropped set recorded in
-- evidence/186-24-feature-vectors-v2-schema.json: momentum_rank_z, volume_rank_z,
-- volatility_rank_z (todo 421), regime_rolling, days_to_month_end (todo 115). The Asian
-- session pair is kept: the vp_sr kernel computes it. No per-row provenance column
-- (feature_vector_id, pipeline_version, feature_factory_version, bar_close_ts,
-- regime_label_source all dropped): lineage = provenance_batch records (D-34, D-24).
--
-- Compression policy intentionally NOT added: bulk_load refuses ranges a scheduled
-- policy_compression job covers, and the build loads old ranges. 186-27 adds the policy after
-- the swap (suggested compress_after about 3 months so a completed 1-year chunk compresses
-- promptly; 186-27's discretion). No retention policy either (derived cache, never wanted).
--
-- chunk_time_interval 1 year, from the warmup-overhead analysis (186-24 evidence JSON); DDL,
-- APR-exempt.
--
-- No VACUUM step: a new empty table, no decompress or recompress (D-16 CI rule does not
-- trigger). Not idempotent on purpose: a second apply fails loudly on CREATE TABLE.

BEGIN;

CREATE TABLE feature_vectors_v2 (
    symbol text NOT NULL,
    tf text NOT NULL,
    bar_ts timestamptz NOT NULL,
    regime text,
    regime_volatility text,
    above_wk_vwap real,
    abs_ret_autocorr_1 real,
    active_demand_zones real,
    active_supply_zones real,
    adx real,
    amd_distribution_direction real,
    amd_manipulation_detected real,
    amd_phase real,
    amihud_illiq_z real,
    aroon_fast real,
    aroon_slow real,
    asian_session_high_dist_atr real,
    asian_session_low_dist_atr real,
    atr_z real,
    bar_close_pos real,
    bars_since_52w_high real,
    bars_since_52w_low real,
    bars_since_extreme_move_fast real,
    bars_since_extreme_move_slow real,
    bars_since_high_fast real,
    bars_since_high_slow real,
    bars_since_last_shift real,
    bars_since_last_sweep real,
    bars_since_low_fast real,
    bars_since_low_slow real,
    bars_since_vol_spike_fast real,
    bars_since_vol_spike_slow real,
    bb_pct_b_fast real,
    bb_pct_b_slow real,
    body_ratio real,
    bos_direction real,
    bos_strength real,
    breaker_block_active real,
    breaker_dist_atr real,
    breakout_volume_product real,
    bsl_dist_atr real,
    bsl_touches real,
    canary_acausal_placebo real,
    canary_constant real,
    canary_near_constant real,
    canary_noise_gaussian real,
    canary_noise_uniform real,
    cci_fast real,
    cci_mid real,
    cci_slow real,
    choch_direction real,
    choch_strength real,
    close_vs_open_direction real,
    cmf real,
    ctf_momentum real,
    ctf_regime_align real,
    ctf_vwap_align real,
    cvd_slope_z real,
    cvd_slope_z_velocity real,
    day_of_month_cos real,
    day_of_month_sin real,
    days_since_quarter_end real,
    demand_dist_atr real,
    demand_freshness real,
    dist_from_high_fast real,
    dist_from_high_slow real,
    dist_from_low_fast real,
    dist_from_low_slow real,
    distance_to_vah_atr real,
    distance_to_val_atr real,
    dollar_vol_z real,
    dow_cos real,
    dow_sin real,
    earnings_season_flag real,
    efficiency_ratio_fast real,
    efficiency_ratio_slow real,
    efficiency_volume_product real,
    equity_beta_z real,
    fib_cluster_strength real,
    flight_quality real,
    fvg_dist_atr real,
    fvg_open_count real,
    fvg_size_atr real,
    gap_filled real,
    gap_z real,
    garch_ratio real,
    garman_klass_vol_velocity real,
    garman_klass_vol_z real,
    high_52w_dist real,
    high_low_corr real,
    hma_slope_z real,
    hmm_churn real,
    hmm_duration real,
    hmm_entropy real,
    hmm_prob_ranging real,
    hmm_prob_trending_down real,
    hmm_prob_trending_up real,
    hmm_regime_prob real,
    hmm_vol_churn real,
    hmm_vol_duration real,
    hmm_vol_entropy real,
    hmm_vol_prob_calm real,
    hmm_vol_prob_elevated real,
    hmm_vol_prob_turbulent real,
    hmm_vol_regime_prob real,
    hour_of_day_cos real,
    hour_of_day_sin real,
    hurst real,
    hv_ratio real,
    hv_z_fast real,
    hv_z_slow real,
    hyg_lqd_ret_z real,
    illiquidity_momentum_product real,
    in_fib_discount_zone real,
    in_london_kz real,
    in_lvn real,
    in_ny_session real,
    in_overlap real,
    informed_flow real,
    intraday_noise_ratio real,
    intraday_ret real,
    lower_wick_ratio real,
    manip_strength real,
    mfi_fast real,
    mfi_slow real,
    minute_of_hour_cos real,
    minute_of_hour_sin real,
    momentum_reversal_z real,
    momentum_trend_product real,
    momentum_vol_regime_product real,
    momentum_z_fast real,
    momentum_z_mid real,
    momentum_z_slow real,
    momentum_z_velocity_fast real,
    momentum_z_velocity_mid real,
    momentum_z_velocity_slow real,
    month_cos real,
    month_position real,
    month_sin real,
    nearest_fib_dist_atr real,
    nearest_fib_ratio real,
    nearest_hvn_above_dist_atr real,
    nearest_hvn_below_dist_atr real,
    nearest_hvn_dist_atr real,
    nearest_level_dist_atr real,
    nearest_lvn_above_dist_atr real,
    nearest_lvn_below_dist_atr real,
    ob_bear_dist_atr real,
    ob_bull_dist_atr real,
    ob_mitigated_flag real,
    ob_mitigation_pct real,
    ob_strength real,
    obv_z real,
    ofi_div real,
    ofi_z real,
    ofi_z_velocity real,
    open_ret real,
    open_vs_intraday real,
    opening_gap_pct real,
    opening_range real,
    opex_flag real,
    overnight_gap real,
    overnight_gap_z real,
    overnight_high_dist_atr real,
    overnight_low_dist_atr real,
    overnight_range_pct real,
    parkinson_vol_velocity real,
    parkinson_vol_z real,
    poc_dist_atr real,
    poc_rolling_dist_atr real,
    poc_session_rolling_divergence_atr real,
    pool_count real,
    power_hour real,
    price_in_value_area real,
    price_percentile_fast real,
    price_percentile_slow real,
    price_position real,
    price_vol_corr_fast real,
    price_vol_corr_slow real,
    prior_session_close_dist_atr real,
    prior_session_high_dist_atr real,
    prior_session_low_dist_atr real,
    quad_witching_flag real,
    quarter_cycle_cos real,
    quarter_cycle_sin real,
    quarter_momentum_product real,
    quarter_position real,
    range_efficiency real,
    range_pct_fast real,
    range_pct_slow real,
    range_position real,
    range_to_close real,
    range_vol_product real,
    range_vs_atr real,
    rate_beta_z real,
    realized_var_ratio_fast real,
    realized_var_ratio_slow real,
    reclaim_velocity real,
    rel_volume real,
    resistance_age_bars real,
    resistance_strength real,
    ret_acf1_z real,
    ret_autocorr_1 real,
    ret_autocorr_5 real,
    ret_div_1h_1d real,
    ret_div_1m_5m real,
    ret_div_5m_1h real,
    ret_kurtosis_z_fast real,
    ret_kurtosis_z_slow real,
    ret_lag_1 real,
    ret_lag_2 real,
    ret_lag_3 real,
    ret_lag_fast real,
    ret_lag_mid real,
    ret_lag_slow real,
    ret_skew_z real,
    ret_vol_product_fast real,
    ret_vol_ratio_fast real,
    reversion_hurst_product real,
    rsi_fast real,
    rsi_mid real,
    rsi_slow real,
    rsi_velocity_fast real,
    rsi_velocity_mid real,
    rsi_velocity_slow real,
    sb_corr_fast real,
    sb_corr_slow real,
    sb_corr_z real,
    session_time_pos real,
    shannon real,
    smc_trend_direction real,
    sr_level_count real,
    sr_resist_dist real,
    sr_support_dist real,
    ssl_dist_atr real,
    ssl_touches real,
    stoch_k_fast real,
    stoch_k_slow real,
    streak_z real,
    struct_accel_bias real,
    struct_energy real,
    structure_integrity real,
    supply_dist_atr real,
    supply_freshness real,
    support_age_bars real,
    support_strength real,
    sweep_detected real,
    sweep_strength real,
    swing_amplitude_expanding real,
    swing_amplitude_intensity real,
    swing_amplitude_ratio real,
    swing_high_age_bars real,
    swing_high_dist_atr real,
    swing_high_type real,
    swing_low_age_bars real,
    swing_low_dist_atr real,
    swing_low_type real,
    swing_pattern real,
    swing_velocity_bars real,
    swing_velocity_bias real,
    swing_volume_confirmation real,
    tdom_cos real,
    tdom_sin real,
    tip_tlt_ret_z real,
    trend_direction real,
    trend_duration_bars real,
    trend_leg_count real,
    trend_strength real,
    true_range_pct real,
    up_vol_body_diff real,
    up_vol_ratio_fast real,
    up_vol_ratio_slow real,
    updown_ratio_fast real,
    updown_ratio_slow real,
    upper_wick_ratio real,
    va_position real,
    va_width_atr real,
    variance_ratio_fast real,
    variance_ratio_momentum_product real,
    variance_ratio_slow real,
    vix_reversion_product real,
    vix_z real,
    vol_acceleration real,
    vol_asymmetry_z real,
    vol_body_product real,
    vol_of_vol real,
    vol_percentile real,
    vol_persistence real,
    vol_range_ratio real,
    vol_ratio real,
    vol_skew_product real,
    vol_std_z real,
    vol_trend_ratio real,
    vol_velocity_z real,
    volume_z real,
    volume_z_velocity real,
    vwap_dev_sigma real,
    vwap_dev_sigma_velocity real,
    week_of_month_cos real,
    week_of_month_sin real,
    week_of_year_cos real,
    week_of_year_sin real,
    weekly_pivot_dist_atr real,
    weekly_r1_dist_atr real,
    weekly_r2_dist_atr real,
    weekly_s1_dist_atr real,
    weekly_s2_dist_atr real,
    yang_zhang_vol_velocity real,
    yang_zhang_vol_z real,
    yield_slope_momentum_product real,
    yield_slope_z real,
    zone_friction_score real,
    PRIMARY KEY (symbol, tf, bar_ts)
);

SELECT create_hypertable('feature_vectors_v2', 'bar_ts', chunk_time_interval => INTERVAL '1 year');

ALTER TABLE feature_vectors_v2 SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'symbol,tf',
    timescaledb.compress_orderby = 'bar_ts'
);

COMMENT ON TABLE feature_vectors_v2 IS 'Rebuilt feature table. Sole writer: bulk_load for the 186-25 rebuild writer. Lineage = provenance_batch records; no per-row provenance column (D-34/D-24). Takes the feature_vectors name at the 186-27 swap. No compression policy during the build (bulk_load refuses ranges a policy covers); 186-27 adds it at the swap.';

COMMIT;
