FROM timescale/timescaledb:latest-pg18

USER root

RUN apk add --no-cache --virtual .build-deps git build-base clang19 llvm19 postgresql18-dev \
    && git clone --branch v0.8.2 https://github.com/pgvector/pgvector.git /tmp/pgvector \
    && cd /tmp/pgvector && make && make install \
    && rm -rf /tmp/pgvector \
    && apk del .build-deps

USER postgres
