"""indicagent_v1 classification seed data: build-date snapshot for Phase 182 (todo 384).

Every node and every per-instrument assignment the seed migration inserts lives here, as
reviewable data. `src/config/classification_seed.py` renders it into
`production/migrations/365_indicagent_v1_classification_seed.sql`; a unit test fails if the
committed migration drifts from the render.

Reviewed per D-06 (executor pass plus an independent AGY pass, reconciled in
`.planning/phases/182-security-classification-hierarchy-todo-384/182-03-REVIEW.md`).

indicagent_v1 is project-owned. Its equity levels 2-4 reuse public GICS sector, industry
group and industry names, but it is not GICS and assigns nothing from GICS (D-03): single
names are mapped from their IBKR industry / category / subcategory triple by judgment of the
company's primary business, ETFs by fund mandate, and futures/FX by contract underlying.

Snapshot rule (D-07): this module describes the build date only. Once migration 365 is
applied, a change to any node or assignment goes through a new close-and-insert migration,
never an edit here.
"""

from src.config.classification_seed import AssignmentSeed, NodeSeed, SchemeSeed
from src.config.classification_service import (
    DEFAULT_SCHEME,
    SOURCE_REF_CONTRACT_SPEC,
    SOURCE_REF_FUND_MANDATE,
    SOURCE_REF_IBKR_REVIEWED,
)

SCHEME = SchemeSeed(
    scheme=DEFAULT_SCHEME,
    name="IndicAgent security classification v1",
    authority="IndicAgent",
    source_ref="phase_182_build",
)

NODES: tuple[NodeSeed, ...] = (
    # Level 1: asset class (D-04)
    NodeSeed("EQ", None, 1, "Equity"),
    NodeSeed("FI", None, 1, "Fixed income"),
    NodeSeed("CMD", None, 1, "Commodity"),
    NodeSeed("CCY", None, 1, "Currency"),
    NodeSeed("CRY", None, 1, "Crypto"),
    NodeSeed("VOL", None, 1, "Volatility"),
    NodeSeed("MA", None, 1, "Multi-asset"),
    # Equity level 2: sector (11 public GICS sector names plus broad market, D-03/D-05)
    NodeSeed("EQ.EN", "EQ", 2, "Energy"),
    NodeSeed("EQ.MAT", "EQ", 2, "Materials"),
    NodeSeed("EQ.IND", "EQ", 2, "Industrials"),
    NodeSeed("EQ.CD", "EQ", 2, "Consumer Discretionary"),
    NodeSeed("EQ.CS", "EQ", 2, "Consumer Staples"),
    NodeSeed("EQ.HC", "EQ", 2, "Health Care"),
    NodeSeed("EQ.FIN", "EQ", 2, "Financials"),
    NodeSeed("EQ.IT", "EQ", 2, "Information Technology"),
    NodeSeed("EQ.COM", "EQ", 2, "Communication Services"),
    NodeSeed("EQ.UTL", "EQ", 2, "Utilities"),
    NodeSeed("EQ.RE", "EQ", 2, "Real Estate"),
    NodeSeed("EQ.BROAD", "EQ", 2, "Broad market (multi-sector)"),
    # Equity level 3: industry group (all 25, public GICS names)
    NodeSeed("EQ.EN.ENERGY", "EQ.EN", 3, "Energy"),
    NodeSeed("EQ.MAT.MATERIALS", "EQ.MAT", 3, "Materials"),
    NodeSeed("EQ.IND.CAPGOODS", "EQ.IND", 3, "Capital Goods"),
    NodeSeed("EQ.IND.COMMSVC", "EQ.IND", 3, "Commercial & Professional Services"),
    NodeSeed("EQ.IND.TRANSPORT", "EQ.IND", 3, "Transportation"),
    NodeSeed("EQ.CD.AUTO", "EQ.CD", 3, "Automobiles & Components"),
    NodeSeed("EQ.CD.DURABLES", "EQ.CD", 3, "Consumer Durables & Apparel"),
    NodeSeed("EQ.CD.SERVICES", "EQ.CD", 3, "Consumer Services"),
    NodeSeed("EQ.CD.RETAIL", "EQ.CD", 3, "Consumer Discretionary Distribution & Retail"),
    NodeSeed("EQ.CS.RETAIL", "EQ.CS", 3, "Consumer Staples Distribution & Retail"),
    NodeSeed("EQ.CS.FOOD", "EQ.CS", 3, "Food, Beverage & Tobacco"),
    NodeSeed("EQ.CS.HOUSEHOLD", "EQ.CS", 3, "Household & Personal Products"),
    NodeSeed("EQ.HC.EQUIPSVC", "EQ.HC", 3, "Health Care Equipment & Services"),
    NodeSeed("EQ.HC.PHARMA", "EQ.HC", 3, "Pharmaceuticals, Biotechnology & Life Sciences"),
    NodeSeed("EQ.FIN.BANKS", "EQ.FIN", 3, "Banks"),
    NodeSeed("EQ.FIN.FINSVC", "EQ.FIN", 3, "Financial Services"),
    NodeSeed("EQ.FIN.INSURANCE", "EQ.FIN", 3, "Insurance"),
    NodeSeed("EQ.IT.SOFTWARE", "EQ.IT", 3, "Software & Services"),
    NodeSeed("EQ.IT.HARDWARE", "EQ.IT", 3, "Technology Hardware & Equipment"),
    NodeSeed("EQ.IT.SEMI", "EQ.IT", 3, "Semiconductors & Semiconductor Equipment"),
    NodeSeed("EQ.COM.TELECOM", "EQ.COM", 3, "Telecommunication Services"),
    NodeSeed("EQ.COM.MEDIA", "EQ.COM", 3, "Media & Entertainment"),
    NodeSeed("EQ.UTL.UTILITIES", "EQ.UTL", 3, "Utilities"),
    NodeSeed("EQ.RE.REITS", "EQ.RE", 3, "Equity Real Estate Investment Trusts (REITs)"),
    NodeSeed("EQ.RE.MGMT", "EQ.RE", 3, "Real Estate Management & Development"),
    # Equity level 4: industry, only where an assignment uses it
    NodeSeed("EQ.EN.ENERGY.EQUIPSVC", "EQ.EN.ENERGY", 4, "Energy Equipment & Services"),
    NodeSeed("EQ.EN.ENERGY.OILGAS", "EQ.EN.ENERGY", 4, "Oil, Gas & Consumable Fuels"),
    NodeSeed("EQ.MAT.MATERIALS.CHEMICALS", "EQ.MAT.MATERIALS", 4, "Chemicals"),
    NodeSeed("EQ.MAT.MATERIALS.METALS", "EQ.MAT.MATERIALS", 4, "Metals & Mining"),
    NodeSeed("EQ.IND.CAPGOODS.AEROSPACE", "EQ.IND.CAPGOODS", 4, "Aerospace & Defense"),
    NodeSeed("EQ.IND.CAPGOODS.CONGLOM", "EQ.IND.CAPGOODS", 4, "Industrial Conglomerates"),
    NodeSeed("EQ.IND.CAPGOODS.ELECTRICAL", "EQ.IND.CAPGOODS", 4, "Electrical Equipment"),
    NodeSeed("EQ.IND.CAPGOODS.MACHINERY", "EQ.IND.CAPGOODS", 4, "Machinery"),
    NodeSeed("EQ.IND.CAPGOODS.TRADING", "EQ.IND.CAPGOODS", 4, "Trading Companies & Distributors"),
    NodeSeed("EQ.IND.COMMSVC.PROFESSIONAL", "EQ.IND.COMMSVC", 4, "Professional Services"),
    NodeSeed("EQ.IND.TRANSPORT.AIRFREIGHT", "EQ.IND.TRANSPORT", 4, "Air Freight & Logistics"),
    NodeSeed("EQ.IND.TRANSPORT.AIRLINES", "EQ.IND.TRANSPORT", 4, "Passenger Airlines"),
    NodeSeed("EQ.IND.TRANSPORT.GROUND", "EQ.IND.TRANSPORT", 4, "Ground Transportation"),
    NodeSeed("EQ.IND.TRANSPORT.MARINE", "EQ.IND.TRANSPORT", 4, "Marine Transportation"),
    NodeSeed("EQ.CD.AUTO.AUTOMOBILES", "EQ.CD.AUTO", 4, "Automobiles"),
    NodeSeed("EQ.CD.AUTO.COMPONENTS", "EQ.CD.AUTO", 4, "Automobile Components"),
    NodeSeed("EQ.CD.DURABLES.HOUSEHOLD", "EQ.CD.DURABLES", 4, "Household Durables"),
    NodeSeed("EQ.CD.DURABLES.LEISURE", "EQ.CD.DURABLES", 4, "Leisure Products"),
    NodeSeed("EQ.CD.DURABLES.TEXTILES", "EQ.CD.DURABLES", 4, "Textiles, Apparel & Luxury Goods"),
    NodeSeed("EQ.CD.SERVICES.HOTELS", "EQ.CD.SERVICES", 4, "Hotels, Restaurants & Leisure"),
    NodeSeed("EQ.CD.RETAIL.BROADLINE", "EQ.CD.RETAIL", 4, "Broadline Retail"),
    NodeSeed("EQ.CD.RETAIL.SPECIALTY", "EQ.CD.RETAIL", 4, "Specialty Retail"),
    NodeSeed("EQ.CS.RETAIL.RETAIL", "EQ.CS.RETAIL", 4, "Consumer Staples Distribution & Retail"),
    NodeSeed("EQ.CS.FOOD.BEVERAGES", "EQ.CS.FOOD", 4, "Beverages"),
    NodeSeed("EQ.CS.FOOD.FOOD", "EQ.CS.FOOD", 4, "Food Products"),
    NodeSeed("EQ.CS.FOOD.TOBACCO", "EQ.CS.FOOD", 4, "Tobacco"),
    NodeSeed("EQ.CS.HOUSEHOLD.HOUSEHOLD", "EQ.CS.HOUSEHOLD", 4, "Household Products"),
    NodeSeed("EQ.HC.EQUIPSVC.EQUIPMENT", "EQ.HC.EQUIPSVC", 4, "Health Care Equipment & Supplies"),
    NodeSeed("EQ.HC.EQUIPSVC.PROVIDERS", "EQ.HC.EQUIPSVC", 4, "Health Care Providers & Services"),
    NodeSeed("EQ.HC.EQUIPSVC.HCTECH", "EQ.HC.EQUIPSVC", 4, "Health Care Technology"),
    NodeSeed("EQ.HC.PHARMA.BIOTECH", "EQ.HC.PHARMA", 4, "Biotechnology"),
    NodeSeed("EQ.HC.PHARMA.PHARMA", "EQ.HC.PHARMA", 4, "Pharmaceuticals"),
    NodeSeed("EQ.FIN.BANKS.BANKS", "EQ.FIN.BANKS", 4, "Banks"),
    NodeSeed("EQ.FIN.FINSVC.FINSVC", "EQ.FIN.FINSVC", 4, "Financial Services"),
    NodeSeed("EQ.FIN.FINSVC.CONSUMER", "EQ.FIN.FINSVC", 4, "Consumer Finance"),
    NodeSeed("EQ.FIN.FINSVC.CAPMKTS", "EQ.FIN.FINSVC", 4, "Capital Markets"),
    NodeSeed(
        "EQ.FIN.FINSVC.MREITS", "EQ.FIN.FINSVC", 4, "Mortgage Real Estate Investment Trusts (REITs)"
    ),
    NodeSeed("EQ.FIN.INSURANCE.INSURANCE", "EQ.FIN.INSURANCE", 4, "Insurance"),
    NodeSeed("EQ.IT.SOFTWARE.ITSVC", "EQ.IT.SOFTWARE", 4, "IT Services"),
    NodeSeed("EQ.IT.SOFTWARE.SOFTWARE", "EQ.IT.SOFTWARE", 4, "Software"),
    NodeSeed(
        "EQ.IT.HARDWARE.TECHHW", "EQ.IT.HARDWARE", 4, "Technology Hardware, Storage & Peripherals"
    ),
    NodeSeed("EQ.IT.SEMI.EQUIP", "EQ.IT.SEMI", 4, "Semiconductors & Semiconductor Equipment"),
    NodeSeed(
        "EQ.COM.TELECOM.DIVERSIFIED", "EQ.COM.TELECOM", 4, "Diversified Telecommunication Services"
    ),
    NodeSeed("EQ.COM.TELECOM.WIRELESS", "EQ.COM.TELECOM", 4, "Wireless Telecommunication Services"),
    NodeSeed("EQ.COM.MEDIA.MEDIA", "EQ.COM.MEDIA", 4, "Media"),
    NodeSeed("EQ.COM.MEDIA.ENTERTAIN", "EQ.COM.MEDIA", 4, "Entertainment"),
    NodeSeed("EQ.COM.MEDIA.INTERACTIVE", "EQ.COM.MEDIA", 4, "Interactive Media & Services"),
    NodeSeed("EQ.UTL.UTILITIES.ELECTRIC", "EQ.UTL.UTILITIES", 4, "Electric Utilities"),
    NodeSeed("EQ.UTL.UTILITIES.WATER", "EQ.UTL.UTILITIES", 4, "Water Utilities"),
    NodeSeed(
        "EQ.UTL.UTILITIES.IPP",
        "EQ.UTL.UTILITIES",
        4,
        "Independent Power and Renewable Electricity Producers",
    ),
    NodeSeed("EQ.RE.REITS.INDUSTRIAL", "EQ.RE.REITS", 4, "Industrial REITs"),
    NodeSeed("EQ.RE.REITS.RETAIL", "EQ.RE.REITS", 4, "Retail REITs"),
    NodeSeed("EQ.RE.REITS.SPECIALIZED", "EQ.RE.REITS", 4, "Specialized REITs"),
    # Non-equity branches (D-04), only where an instrument is assigned
    NodeSeed("FI.BROAD", "FI", 2, "Broad and aggregate bonds"),
    NodeSeed("FI.RATES", "FI", 2, "Government rates"),
    NodeSeed("FI.CREDIT", "FI", 2, "Corporate credit"),
    NodeSeed("FI.CREDIT.IG", "FI.CREDIT", 3, "Investment grade"),
    NodeSeed("FI.CREDIT.HY", "FI.CREDIT", 3, "High yield"),
    NodeSeed("FI.MUNI", "FI", 2, "Municipal"),
    NodeSeed("FI.INFL", "FI", 2, "Inflation-linked"),
    NodeSeed("FI.PREF", "FI", 2, "Preferred securities"),
    NodeSeed("FI.CONV", "FI", 2, "Convertible securities"),
    NodeSeed("FI.EM", "FI", 2, "Emerging-market debt"),
    NodeSeed("CMD.BROAD", "CMD", 2, "Broad commodities"),
    NodeSeed("CMD.ENERGY", "CMD", 2, "Energy"),
    NodeSeed("CMD.PREC", "CMD", 2, "Precious metals"),
    NodeSeed("CMD.INDMET", "CMD", 2, "Industrial metals"),
    NodeSeed("CMD.AG", "CMD", 2, "Agriculture"),
    NodeSeed("CCY.USD", "CCY", 2, "US dollar"),
    NodeSeed("CCY.DM", "CCY", 2, "Developed-market currencies"),
    NodeSeed("CRY.BTC", "CRY", 2, "Bitcoin"),
    NodeSeed("CRY.ETH", "CRY", 2, "Ether"),
    NodeSeed("VOL.EQUITY", "VOL", 2, "Equity index volatility"),
    NodeSeed("MA.ALT", "MA", 2, "Alternatives, market-neutral and managed strategies"),
)

ASSIGNMENTS: tuple[AssignmentSeed, ...] = (
    # Single names: IBKR industry / category / subcategory, reviewed (D-06)
    AssignmentSeed(
        "F",
        "EQ.CD.AUTO.AUTOMOBILES",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Auto Manufacturers / Auto-Cars/Light Trucks",
    ),
    AssignmentSeed(
        "GM",
        "EQ.CD.AUTO.AUTOMOBILES",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Auto Manufacturers / Auto-Cars/Light Trucks",
    ),
    AssignmentSeed(
        "RIVN",
        "EQ.CD.AUTO.AUTOMOBILES",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Auto Manufacturers / Auto-Cars/Light Trucks",
    ),
    AssignmentSeed(
        "TSLA",
        "EQ.CD.AUTO.AUTOMOBILES",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Auto Manufacturers / Auto-Cars/Light Trucks",
    ),
    AssignmentSeed(
        "THRM",
        "EQ.CD.AUTO.COMPONENTS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Auto Parts&Equipment / Auto/Trk Prts&Equip-Orig",
    ),
    AssignmentSeed(
        "DHI",
        "EQ.CD.DURABLES.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Home Builders / Bldg-Residential/Commer",
    ),
    AssignmentSeed(
        "GRBK",
        "EQ.CD.DURABLES.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Home Builders / Bldg-Residential/Commer",
    ),
    AssignmentSeed(
        "LEN",
        "EQ.CD.DURABLES.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Home Builders / Bldg-Residential/Commer",
    ),
    AssignmentSeed(
        "MTH",
        "EQ.CD.DURABLES.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Home Builders / Bldg-Residential/Commer",
    ),
    AssignmentSeed(
        "NVR",
        "EQ.CD.DURABLES.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Home Builders / Bldg-Residential/Commer",
    ),
    AssignmentSeed(
        "TOL",
        "EQ.CD.DURABLES.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Home Builders / Bldg-Residential/Commer",
    ),
    AssignmentSeed(
        "WHR",
        "EQ.CD.DURABLES.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Home Furnishings / Appliances",
    ),
    AssignmentSeed(
        "RGR",
        "EQ.CD.DURABLES.LEISURE",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Miscellaneous Manufactur / Firearms&Ammunition",
        "Consumer firearms maker; firearms sold to consumers are a leisure product, not industrial manufacturing",
    ),
    AssignmentSeed(
        "CRI",
        "EQ.CD.DURABLES.TEXTILES",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Apparel / Apparel Manufacturers",
    ),
    AssignmentSeed(
        "AMZN",
        "EQ.CD.RETAIL.BROADLINE",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Internet / E-Commerce/Products",
        "Largest segment by revenue is online retail; Broadline Retail rather than a communications internet node",
    ),
    AssignmentSeed(
        "WSHP",
        "EQ.CD.RETAIL.BROADLINE",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Internet / E-Commerce/Products",
        "Operates a social e-commerce retail platform; Broadline Retail, as for AMZN",
    ),
    AssignmentSeed(
        "BKE",
        "EQ.CD.RETAIL.SPECIALTY",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Retail / Retail-Apparel/Shoe",
    ),
    AssignmentSeed(
        "HD",
        "EQ.CD.RETAIL.SPECIALTY",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Retail / Retail-Building Products",
    ),
    AssignmentSeed(
        "WSM",
        "EQ.CD.RETAIL.SPECIALTY",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Retail / Retail-Home Furnishings",
    ),
    AssignmentSeed(
        "BKNG",
        "EQ.CD.SERVICES.HOTELS",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Internet / E-Commerce/Services",
        "Online travel agency; its revenue is hotel and travel bookings, so Hotels, Restaurants & Leisure rather than an internet node",
    ),
    AssignmentSeed(
        "MAR",
        "EQ.CD.SERVICES.HOTELS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Lodging / Hotels&Motels",
    ),
    AssignmentSeed(
        "MCD",
        "EQ.CD.SERVICES.HOTELS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Retail / Retail-Restaurants",
        "Restaurants are Hotels, Restaurants & Leisure, not a retail industry",
    ),
    AssignmentSeed(
        "MGM",
        "EQ.CD.SERVICES.HOTELS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Lodging / Casino Hotels",
    ),
    AssignmentSeed(
        "RCL",
        "EQ.CD.SERVICES.HOTELS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Leisure Time / Cruise Lines",
    ),
    AssignmentSeed(
        "DIS",
        "EQ.COM.MEDIA.ENTERTAIN",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Media / Multimedia",
    ),
    AssignmentSeed(
        "NFLX",
        "EQ.COM.MEDIA.ENTERTAIN",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Internet / Internet Content-Entmnt",
        "Subscription video streaming; Entertainment, unlike META's ad-funded interactive media",
    ),
    AssignmentSeed(
        "GOOGL",
        "EQ.COM.MEDIA.INTERACTIVE",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Internet / Web Portals/ISP",
    ),
    AssignmentSeed(
        "META",
        "EQ.COM.MEDIA.INTERACTIVE",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Internet / Internet Content-Entmnt",
    ),
    AssignmentSeed(
        "CMCSA",
        "EQ.COM.MEDIA.MEDIA",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Media / Cable/Satellite TV",
    ),
    AssignmentSeed(
        "SSP",
        "EQ.COM.MEDIA.MEDIA",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Media / Multimedia",
        "Local TV broadcasting funded by advertising and retransmission fees; Media, unlike DIS's studios and parks",
    ),
    AssignmentSeed(
        "T",
        "EQ.COM.TELECOM.DIVERSIFIED",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Telecommunications / Telephone-Integrated",
    ),
    AssignmentSeed(
        "VZ",
        "EQ.COM.TELECOM.DIVERSIFIED",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Telecommunications / Telephone-Integrated",
    ),
    AssignmentSeed(
        "TMUS",
        "EQ.COM.TELECOM.WIRELESS",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Telecommunications / Cellular Telecom",
    ),
    AssignmentSeed(
        "KO",
        "EQ.CS.FOOD.BEVERAGES",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Beverages / Beverages-Non-alcoholic",
    ),
    AssignmentSeed(
        "PEP",
        "EQ.CS.FOOD.BEVERAGES",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Beverages / Beverages-Non-alcoholic",
    ),
    AssignmentSeed(
        "ADM",
        "EQ.CS.FOOD.FOOD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Agriculture / Agricultural Operations",
    ),
    AssignmentSeed(
        "DAR",
        "EQ.CS.FOOD.FOOD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Agriculture / Pastoral&Agricultural",
    ),
    AssignmentSeed(
        "JBS",
        "EQ.CS.FOOD.FOOD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Food / Food-Meat Products",
    ),
    AssignmentSeed(
        "MO",
        "EQ.CS.FOOD.TOBACCO",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Agriculture / Tobacco",
        "Tobacco is its own industry, not agriculture",
    ),
    AssignmentSeed(
        "PM",
        "EQ.CS.FOOD.TOBACCO",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Agriculture / Tobacco",
        "Tobacco is its own industry, not agriculture",
    ),
    AssignmentSeed(
        "CENT",
        "EQ.CS.HOUSEHOLD.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Housewares / Housewares",
        "Lawn, garden and pet consumables sold through grocery and mass retail; staples, not discretionary housewares",
    ),
    AssignmentSeed(
        "PG",
        "EQ.CS.HOUSEHOLD.HOUSEHOLD",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Cosmetics/Personal Care / Cosmetics&Toiletries",
    ),
    AssignmentSeed(
        "CASY",
        "EQ.CS.RETAIL.RETAIL",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Retail / Retail-Convenience Store",
        "Convenience stores selling fuel, groceries and prepared food; Consumer Staples Distribution & Retail",
    ),
    AssignmentSeed(
        "COST",
        "EQ.CS.RETAIL.RETAIL",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Retail / Retail-Discount",
        "Warehouse club selling mostly food and household staples; Consumer Staples Distribution & Retail",
    ),
    AssignmentSeed(
        "UNFI",
        "EQ.CS.RETAIL.RETAIL",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Food / Food-Wholesale/Distrib",
        "Grocery wholesale distributor; food distribution sits in Consumer Staples Distribution & Retail, not Food Products",
    ),
    AssignmentSeed(
        "WMT",
        "EQ.CS.RETAIL.RETAIL",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Retail / Retail-Discount",
        "Grocery and general-merchandise discount retailer, majority grocery; Consumer Staples Distribution & Retail",
    ),
    AssignmentSeed(
        "SLB",
        "EQ.EN.ENERGY.EQUIPSVC",
        SOURCE_REF_IBKR_REVIEWED,
        "Energy / Oil&Gas Services / Oil-Field Services",
    ),
    AssignmentSeed(
        "CCJ",
        "EQ.EN.ENERGY.OILGAS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Mining / Non-Ferrous Metals",
        "Uranium miner and nuclear-fuel supplier; uranium is a consumable fuel, so Oil, Gas & Consumable Fuels (Energy) rather than non-ferrous metals mining",
    ),
    AssignmentSeed(
        "COP",
        "EQ.EN.ENERGY.OILGAS",
        SOURCE_REF_IBKR_REVIEWED,
        "Energy / Oil&Gas / Oil Comp-Explor&Prodtn",
    ),
    AssignmentSeed(
        "CVX",
        "EQ.EN.ENERGY.OILGAS",
        SOURCE_REF_IBKR_REVIEWED,
        "Energy / Oil&Gas / Oil Comp-Integrated",
    ),
    AssignmentSeed(
        "EPD", "EQ.EN.ENERGY.OILGAS", SOURCE_REF_IBKR_REVIEWED, "Energy / Pipelines / Pipelines"
    ),
    AssignmentSeed(
        "INSW",
        "EQ.EN.ENERGY.OILGAS",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Marine",
        "Crude and product tanker owner; tanker shipping is oil storage and transportation, unlike Kirby's diversified marine transport",
    ),
    AssignmentSeed(
        "KMI", "EQ.EN.ENERGY.OILGAS", SOURCE_REF_IBKR_REVIEWED, "Energy / Pipelines / Pipelines"
    ),
    AssignmentSeed(
        "OXY",
        "EQ.EN.ENERGY.OILGAS",
        SOURCE_REF_IBKR_REVIEWED,
        "Energy / Oil&Gas / Oil Comp-Explor&Prodtn",
    ),
    AssignmentSeed(
        "WMB", "EQ.EN.ENERGY.OILGAS", SOURCE_REF_IBKR_REVIEWED, "Energy / Pipelines / Pipelines"
    ),
    AssignmentSeed(
        "XOM",
        "EQ.EN.ENERGY.OILGAS",
        SOURCE_REF_IBKR_REVIEWED,
        "Energy / Oil&Gas / Oil Comp-Integrated",
    ),
    AssignmentSeed(
        "BAC",
        "EQ.FIN.BANKS.BANKS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Banks / Diversified Banking Inst",
    ),
    AssignmentSeed(
        "COFS",
        "EQ.FIN.BANKS.BANKS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Banks / Commer Banks-Central US",
    ),
    AssignmentSeed(
        "JPM",
        "EQ.FIN.BANKS.BANKS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Banks / Diversified Banking Inst",
    ),
    AssignmentSeed(
        "USB",
        "EQ.FIN.BANKS.BANKS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Banks / Super-Regional Banks-US",
    ),
    AssignmentSeed(
        "BLK",
        "EQ.FIN.FINSVC.CAPMKTS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Diversified Finan Serv / Invest Mgmnt/Advis Serv",
    ),
    AssignmentSeed(
        "COIN",
        "EQ.FIN.FINSVC.CAPMKTS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Diversified Finan Serv / Finance-Other Services",
    ),
    AssignmentSeed(
        "FRHC",
        "EQ.FIN.FINSVC.CAPMKTS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Diversified Finan Serv / Finance-Invest Bnkr/Brkr",
    ),
    AssignmentSeed(
        "GS",
        "EQ.FIN.FINSVC.CAPMKTS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Banks / Diversified Banking Inst",
        "Investment banking, trading and asset management dominate revenue; Capital Markets rather than a deposit-funded lending bank",
    ),
    AssignmentSeed(
        "MS",
        "EQ.FIN.FINSVC.CAPMKTS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Banks / Diversified Banking Inst",
        "Wealth management and institutional securities dominate revenue; Capital Markets rather than a deposit-funded lending bank",
    ),
    AssignmentSeed(
        "RJF",
        "EQ.FIN.FINSVC.CAPMKTS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Diversified Finan Serv / Invest Mgmnt/Advis Serv",
    ),
    AssignmentSeed(
        "AXP",
        "EQ.FIN.FINSVC.CONSUMER",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Diversified Finan Serv / Finance-Credit Card",
    ),
    AssignmentSeed(
        "SLM",
        "EQ.FIN.FINSVC.CONSUMER",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Diversified Finan Serv / Finance-Consumer Loans",
    ),
    AssignmentSeed(
        "MARA",
        "EQ.FIN.FINSVC.FINSVC",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Investment Companies / Investment Companies",
    ),
    AssignmentSeed(
        "MSTR",
        "EQ.FIN.FINSVC.FINSVC",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Software / Enterprise Software/Serv",
        "Bitcoin treasury company; bitcoin holdings dwarf the legacy software business in both balance sheet and return driver",
    ),
    AssignmentSeed(
        "PURR",
        "EQ.FIN.FINSVC.FINSVC",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Diversified Finan Serv / Finance-Other Services",
        "Digital-asset treasury company holding HYPE tokens; a holding vehicle, not an exchange or broker like COIN",
    ),
    AssignmentSeed(
        "RIOT",
        "EQ.FIN.FINSVC.FINSVC",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Investment Companies / Investment Companies",
    ),
    AssignmentSeed(
        "V",
        "EQ.FIN.FINSVC.FINSVC",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Diversified Finan Serv / Finance-Credit Card",
        "Payment network that does not lend; transaction processing is Financial Services, not Consumer Finance",
    ),
    AssignmentSeed(
        "NLY",
        "EQ.FIN.FINSVC.MREITS",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / REITS / REITS-Mortgage",
        "Mortgage REITs hold mortgage credit, not property; they sit in Financials, not Real Estate",
    ),
    AssignmentSeed(
        "PGR",
        "EQ.FIN.INSURANCE.INSURANCE",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Insurance / Property/Casualty Ins",
    ),
    AssignmentSeed(
        "SPNT",
        "EQ.FIN.INSURANCE.INSURANCE",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Insurance / Reinsurance",
    ),
    AssignmentSeed(
        "TRV",
        "EQ.FIN.INSURANCE.INSURANCE",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / Insurance / Property/Casualty Ins",
    ),
    AssignmentSeed(
        "GKOS",
        "EQ.HC.EQUIPSVC.EQUIPMENT",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Healthcare-Products / Medical Products",
    ),
    AssignmentSeed(
        "ISRG",
        "EQ.HC.EQUIPSVC.EQUIPMENT",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Healthcare-Products / Medical Instruments",
    ),
    AssignmentSeed(
        "DOCS",
        "EQ.HC.EQUIPSVC.HCTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Software / Medical Information Sys",
        "Online network and software for physicians; its customers and revenue are in health care, so Health Care Technology",
    ),
    AssignmentSeed(
        "CVS",
        "EQ.HC.EQUIPSVC.PROVIDERS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Pharmaceuticals / Pharmacy Services",
        "Pharmacy benefit management, insurance (Aetna) and retail pharmacy; a health-care services company, not a drug maker",
    ),
    AssignmentSeed(
        "ELV",
        "EQ.HC.EQUIPSVC.PROVIDERS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Healthcare-Services / Medical-HMO",
    ),
    AssignmentSeed(
        "HCA",
        "EQ.HC.EQUIPSVC.PROVIDERS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Healthcare-Services / Medical-Hospitals",
    ),
    AssignmentSeed(
        "PGNY",
        "EQ.HC.EQUIPSVC.PROVIDERS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Commercial Services / Commercial Services",
        "Fertility benefits manager paid by employers for treatment; a health-care services business",
    ),
    AssignmentSeed(
        "TDOC",
        "EQ.HC.EQUIPSVC.PROVIDERS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Healthcare-Services / Medical-Outptnt/Home Med",
    ),
    AssignmentSeed(
        "THC",
        "EQ.HC.EQUIPSVC.PROVIDERS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Healthcare-Services / Medical-Hospitals",
    ),
    AssignmentSeed(
        "UNH",
        "EQ.HC.EQUIPSVC.PROVIDERS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Healthcare-Services / Medical-HMO",
    ),
    AssignmentSeed(
        "ALMS",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "AVBP",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "BEAM",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "BNTX",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "CRSP",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "EXEL",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "GILD",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "REGN",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "RVMD",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "UPB",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "VRTX",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Medical-Biomedical/Gene",
    ),
    AssignmentSeed(
        "JNJ",
        "EQ.HC.PHARMA.PHARMA",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Pharmaceuticals / Medical-Drugs",
    ),
    AssignmentSeed(
        "LLY",
        "EQ.HC.PHARMA.PHARMA",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Pharmaceuticals / Medical-Drugs",
    ),
    AssignmentSeed(
        "MRK",
        "EQ.HC.PHARMA.PHARMA",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Pharmaceuticals / Medical-Drugs",
    ),
    AssignmentSeed(
        "PFE",
        "EQ.HC.PHARMA.PHARMA",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Pharmaceuticals / Medical-Drugs",
    ),
    AssignmentSeed(
        "VNDA",
        "EQ.HC.PHARMA.PHARMA",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Pharmaceuticals / Medical-Drugs",
    ),
    AssignmentSeed(
        "BA",
        "EQ.IND.CAPGOODS.AEROSPACE",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Aerospace/Defense / Aerospace/Defense",
    ),
    AssignmentSeed(
        "GE",
        "EQ.IND.CAPGOODS.AEROSPACE",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Aerospace/Defense / Aerospace/Defense-Equip",
    ),
    AssignmentSeed(
        "LMT",
        "EQ.IND.CAPGOODS.AEROSPACE",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Aerospace/Defense / Aerospace/Defense",
    ),
    AssignmentSeed(
        "RTX",
        "EQ.IND.CAPGOODS.AEROSPACE",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Aerospace/Defense / Aerospace/Defense",
    ),
    AssignmentSeed(
        "TXT",
        "EQ.IND.CAPGOODS.AEROSPACE",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Miscellaneous Manufactur / Diversified Manufact Op",
        "Textron's largest segments are Cessna/Beechcraft aviation, Bell helicopters and defense systems",
    ),
    AssignmentSeed(
        "HON",
        "EQ.IND.CAPGOODS.CONGLOM",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Electronics / Instruments-Controls",
        "Honeywell spans aerospace, building automation and industrial automation; a conglomerate, not an electronics maker",
    ),
    AssignmentSeed(
        "MMM",
        "EQ.IND.CAPGOODS.CONGLOM",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Miscellaneous Manufactur / Diversified Manufact Op",
    ),
    AssignmentSeed(
        "ARRY",
        "EQ.IND.CAPGOODS.ELECTRICAL",
        SOURCE_REF_IBKR_REVIEWED,
        "Energy / Energy-Alternate Sources / Energy-Alternate Sources",
        "Makes solar tracker equipment; an equipment manufacturer, not an energy producer",
    ),
    AssignmentSeed(
        "EMR",
        "EQ.IND.CAPGOODS.ELECTRICAL",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Electronics / Electronic Measur Instr",
        "Automation and electrical equipment manufacturer rather than electronic instruments",
    ),
    AssignmentSeed(
        "GEV",
        "EQ.IND.CAPGOODS.ELECTRICAL",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Machinery-Constr&Mining / Machinery-Electric Util",
    ),
    AssignmentSeed(
        "ATMU",
        "EQ.IND.CAPGOODS.MACHINERY",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Electronics / Electronic Compo-Misc",
        "Makes engine and industrial filtration products; machinery components, not electronics",
    ),
    AssignmentSeed(
        "CAT",
        "EQ.IND.CAPGOODS.MACHINERY",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Machinery-Constr&Mining / Machinery-Constr&Mining",
    ),
    AssignmentSeed(
        "DE",
        "EQ.IND.CAPGOODS.MACHINERY",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Machinery-Diversified / Machinery-Farm",
    ),
    AssignmentSeed(
        "WCC",
        "EQ.IND.CAPGOODS.TRADING",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Distribution/Wholesale / Distribution/Wholesale",
        "Electrical and communications products distributor to industrial and utility customers",
    ),
    AssignmentSeed(
        "ACTG",
        "EQ.IND.COMMSVC.PROFESSIONAL",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Commercial Services / Consulting Services",
        "Patent licensing plus acquired operating businesses; the consulting/commercial services triple maps to Professional Services, an Industrials industry",
    ),
    AssignmentSeed(
        "FDX",
        "EQ.IND.TRANSPORT.AIRFREIGHT",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Services",
    ),
    AssignmentSeed(
        "UPS",
        "EQ.IND.TRANSPORT.AIRFREIGHT",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Services",
    ),
    AssignmentSeed(
        "DAL",
        "EQ.IND.TRANSPORT.AIRLINES",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Cyclical / Airlines / Airlines",
        "Passenger airline; airlines are a Transportation industry, an Industrials group",
    ),
    AssignmentSeed(
        "CSX",
        "EQ.IND.TRANSPORT.GROUND",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Rail",
    ),
    AssignmentSeed(
        "JBHT",
        "EQ.IND.TRANSPORT.GROUND",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Truck",
    ),
    AssignmentSeed(
        "ODFL",
        "EQ.IND.TRANSPORT.GROUND",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Truck",
    ),
    AssignmentSeed(
        "R",
        "EQ.IND.TRANSPORT.GROUND",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Services",
        "Truck leasing, dedicated trucking and supply chain; ground freight, not an air parcel network",
    ),
    AssignmentSeed(
        "UBER",
        "EQ.IND.TRANSPORT.GROUND",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Internet / E-Commerce/Services",
        "Ride-hailing and delivery; passenger ground transportation is the primary business, not internet e-commerce services",
    ),
    AssignmentSeed(
        "UNP",
        "EQ.IND.TRANSPORT.GROUND",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Rail",
    ),
    AssignmentSeed(
        "KEX",
        "EQ.IND.TRANSPORT.MARINE",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Transportation / Transport-Marine",
    ),
    AssignmentSeed(
        "AAPL",
        "EQ.IT.HARDWARE.TECHHW",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Computers / Computers",
    ),
    AssignmentSeed(
        "AMD",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Semiconductors / Electronic Compo-Semicon",
    ),
    AssignmentSeed(
        "ASML",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Semiconductors / Semiconductor Equipment",
    ),
    AssignmentSeed(
        "AVGO",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Semiconductors / Electronic Compo-Semicon",
    ),
    AssignmentSeed(
        "CRUS",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Semiconductors / Semicon Compo-Intg Circu",
    ),
    AssignmentSeed(
        "ENPH",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Energy / Energy-Alternate Sources / Energy-Alternate Sources",
        "Designs semiconductor-based microinverters and battery electronics; a semiconductor-based device maker, not an energy producer",
    ),
    AssignmentSeed(
        "FSLR",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Energy / Energy-Alternate Sources / Energy-Alternate Sources",
        "Manufactures thin-film solar modules on a semiconductor process; a module maker, not an energy producer",
    ),
    AssignmentSeed(
        "NVDA",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Semiconductors / Electronic Compo-Semicon",
    ),
    AssignmentSeed(
        "QCOM",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Semiconductors / Semicon Compo-Intg Circu",
    ),
    AssignmentSeed(
        "TSM",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Semiconductors / Semicon Compo-Intg Circu",
    ),
    AssignmentSeed(
        "CRWV",
        "EQ.IT.SOFTWARE.ITSVC",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Software / Computer Software",
        "Rents GPU cloud capacity (infrastructure as a service); IT Services, not packaged software",
    ),
    AssignmentSeed(
        "CRM",
        "EQ.IT.SOFTWARE.SOFTWARE",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Software / Enterprise Software/Serv",
    ),
    AssignmentSeed(
        "CRWD",
        "EQ.IT.SOFTWARE.SOFTWARE",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Computers / Computer Data Security",
        "Cloud security software subscriptions; Software, not computer hardware",
    ),
    AssignmentSeed(
        "MSFT",
        "EQ.IT.SOFTWARE.SOFTWARE",
        SOURCE_REF_IBKR_REVIEWED,
        "Technology / Software / Applications Software",
    ),
    AssignmentSeed(
        "PANW",
        "EQ.IT.SOFTWARE.SOFTWARE",
        SOURCE_REF_IBKR_REVIEWED,
        "Communications / Internet / Internet Security",
        "Network and cloud security software and firewalls; Software, not a communications internet node",
    ),
    AssignmentSeed(
        "CTVA",
        "EQ.MAT.MATERIALS.CHEMICALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Consumer, Non-cyclical / Biotechnology / Agricultural Biotech",
        "Seeds and crop-protection chemicals; the agricultural-chemicals business is the primary one, so Chemicals (Materials) rather than a health-care biotech node",
    ),
    AssignmentSeed(
        "DD",
        "EQ.MAT.MATERIALS.CHEMICALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Industrial / Miscellaneous Manufactur / Diversified Manufact Op",
        "DuPont's businesses are specialty materials and chemicals, not diversified industrial manufacturing",
    ),
    AssignmentSeed(
        "DOW",
        "EQ.MAT.MATERIALS.CHEMICALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Chemicals / Chemicals-Diversified",
    ),
    AssignmentSeed(
        "ECL",
        "EQ.MAT.MATERIALS.CHEMICALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Chemicals / Chemicals-Specialty",
    ),
    AssignmentSeed(
        "LIN",
        "EQ.MAT.MATERIALS.CHEMICALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Chemicals / Industrial Gases",
    ),
    AssignmentSeed(
        "NTR",
        "EQ.MAT.MATERIALS.CHEMICALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Chemicals / Agricultural Chemicals",
    ),
    AssignmentSeed(
        "SHW",
        "EQ.MAT.MATERIALS.CHEMICALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Chemicals / Coatings/Paint",
    ),
    AssignmentSeed(
        "AA",
        "EQ.MAT.MATERIALS.METALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Mining / Metal-Aluminum",
    ),
    AssignmentSeed(
        "BHP",
        "EQ.MAT.MATERIALS.METALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Mining / Diversified Minerals",
    ),
    AssignmentSeed(
        "CSTM",
        "EQ.MAT.MATERIALS.METALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Mining / Metal-Aluminum",
    ),
    AssignmentSeed(
        "FCX",
        "EQ.MAT.MATERIALS.METALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Mining / Metal-Copper",
    ),
    AssignmentSeed(
        "NEM",
        "EQ.MAT.MATERIALS.METALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Mining / Gold Mining",
    ),
    AssignmentSeed(
        "NUE",
        "EQ.MAT.MATERIALS.METALS",
        SOURCE_REF_IBKR_REVIEWED,
        "Basic Materials / Iron/Steel / Steel-Producers",
    ),
    AssignmentSeed(
        "PLD",
        "EQ.RE.REITS.INDUSTRIAL",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / REITS / REITS-Warehouse/Industr",
    ),
    AssignmentSeed(
        "SPG",
        "EQ.RE.REITS.RETAIL",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / REITS / REITS-Regional Malls",
    ),
    AssignmentSeed(
        "AMT",
        "EQ.RE.REITS.SPECIALIZED",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / REITS / REITS-Diversified",
        "Cell-tower REIT; towers are a Specialized REIT, not a Diversified REIT",
    ),
    AssignmentSeed(
        "EQIX",
        "EQ.RE.REITS.SPECIALIZED",
        SOURCE_REF_IBKR_REVIEWED,
        "Financial / REITS / REITS-Diversified",
        "Data-center REIT; data centers are a Specialized REIT, not a Diversified REIT",
    ),
    AssignmentSeed(
        "AEP",
        "EQ.UTL.UTILITIES.ELECTRIC",
        SOURCE_REF_IBKR_REVIEWED,
        "Utilities / Electric / Electric-Integrated",
    ),
    AssignmentSeed(
        "DUK",
        "EQ.UTL.UTILITIES.ELECTRIC",
        SOURCE_REF_IBKR_REVIEWED,
        "Utilities / Electric / Electric-Integrated",
    ),
    AssignmentSeed(
        "ETR",
        "EQ.UTL.UTILITIES.ELECTRIC",
        SOURCE_REF_IBKR_REVIEWED,
        "Utilities / Electric / Electric-Integrated",
    ),
    AssignmentSeed(
        "NEE",
        "EQ.UTL.UTILITIES.ELECTRIC",
        SOURCE_REF_IBKR_REVIEWED,
        "Utilities / Electric / Electric-Integrated",
    ),
    AssignmentSeed(
        "SO",
        "EQ.UTL.UTILITIES.ELECTRIC",
        SOURCE_REF_IBKR_REVIEWED,
        "Utilities / Electric / Electric-Integrated",
    ),
    AssignmentSeed(
        "VST",
        "EQ.UTL.UTILITIES.IPP",
        SOURCE_REF_IBKR_REVIEWED,
        "Utilities / Electric / Independ Power Producer",
    ),
    AssignmentSeed(
        "AWK", "EQ.UTL.UTILITIES.WATER", SOURCE_REF_IBKR_REVIEWED, "Utilities / Water / Water"
    ),
    AssignmentSeed(
        "WTRG", "EQ.UTL.UTILITIES.WATER", SOURCE_REF_IBKR_REVIEWED, "Utilities / Water / Water"
    ),
    # ETFs and funds: fund mandate, deepest level the mandate pins down (D-05)
    AssignmentSeed(
        "FXA",
        "CCY.DM",
        SOURCE_REF_FUND_MANDATE,
        "Invesco CurrencyShares Australian Dollar Trust: Australian dollar deposits",
    ),
    AssignmentSeed(
        "FXC",
        "CCY.DM",
        SOURCE_REF_FUND_MANDATE,
        "Invesco CurrencyShares Canadian Dollar Trust: Canadian dollar deposits",
    ),
    AssignmentSeed(
        "FXE",
        "CCY.DM",
        SOURCE_REF_FUND_MANDATE,
        "Invesco CurrencyShares Euro Currency Trust: euro deposits",
    ),
    AssignmentSeed(
        "FXY",
        "CCY.DM",
        SOURCE_REF_FUND_MANDATE,
        "Invesco CurrencyShares Japanese Yen Trust: yen deposits",
    ),
    AssignmentSeed(
        "UUP",
        "CCY.USD",
        SOURCE_REF_FUND_MANDATE,
        "Invesco DB US Dollar Index Bullish Fund: long USD index futures",
    ),
    AssignmentSeed(
        "DBA",
        "CMD.AG",
        SOURCE_REF_FUND_MANDATE,
        "Invesco DB Agriculture Fund: agricultural commodity futures",
    ),
    AssignmentSeed(
        "DBC",
        "CMD.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Invesco DB Commodity Index Tracking Fund: futures across energy, metals and agriculture",
    ),
    AssignmentSeed(
        "DBB",
        "CMD.INDMET",
        SOURCE_REF_FUND_MANDATE,
        "Invesco DB Base Metals Fund: aluminum, zinc and copper futures",
    ),
    AssignmentSeed("GLD", "CMD.PREC", SOURCE_REF_FUND_MANDATE, "SPDR Gold Shares: physical gold"),
    AssignmentSeed(
        "PPLT",
        "CMD.PREC",
        SOURCE_REF_FUND_MANDATE,
        "abrdn Physical Platinum Shares ETF: physical platinum",
    ),
    AssignmentSeed(
        "SLV", "CMD.PREC", SOURCE_REF_FUND_MANDATE, "iShares Silver Trust: physical silver"
    ),
    AssignmentSeed(
        "IBIT", "CRY.BTC", SOURCE_REF_FUND_MANDATE, "iShares Bitcoin Trust ETF: spot bitcoin"
    ),
    AssignmentSeed(
        "ETHA", "CRY.ETH", SOURCE_REF_FUND_MANDATE, "iShares Ethereum Trust ETF: spot ether"
    ),
    AssignmentSeed(
        "ARKK",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "ARK Innovation ETF: actively managed disruptive innovation across tech, health care, fintech",
    ),
    AssignmentSeed(
        "DIA",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "SPDR Dow Jones Industrial Average ETF: 30 US large caps across sectors",
    ),
    AssignmentSeed(
        "EEM",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI Emerging Markets ETF: emerging-market equities, all sectors",
    ),
    AssignmentSeed(
        "EFA",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI EAFE ETF: developed markets ex US/Canada, all sectors (geography is tag territory)",
    ),
    AssignmentSeed(
        "EWG",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI Germany ETF: German equities, all sectors",
    ),
    AssignmentSeed(
        "EWJ",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI Japan ETF: Japanese equities, all sectors",
    ),
    AssignmentSeed(
        "EWT",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI Taiwan ETF: Taiwanese equities, all sectors (semiconductor-heavy; country fund)",
    ),
    AssignmentSeed(
        "EWY",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI South Korea ETF: Korean equities, all sectors",
    ),
    AssignmentSeed(
        "EWZ",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI Brazil ETF: Brazilian equities, all sectors",
    ),
    AssignmentSeed(
        "EZU",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI Eurozone ETF: eurozone equities, all sectors",
    ),
    AssignmentSeed(
        "FXI",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares China Large-Cap ETF: 50 largest Hong Kong-listed Chinese companies, all sectors",
    ),
    AssignmentSeed(
        "ICLN",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares Global Clean Energy ETF: renewable utilities, independent power producers, solar manufacturers and electrical equipment; multi-sector thematic",
    ),
    AssignmentSeed(
        "INDA",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI India ETF: Indian equities, all sectors",
    ),
    AssignmentSeed(
        "IPO",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Renaissance IPO ETF: recent US IPOs, all sectors",
    ),
    AssignmentSeed(
        "IWM",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares Russell 2000 ETF: US small caps across all sectors",
    ),
    AssignmentSeed(
        "KWEB",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "KraneShares CSI China Internet ETF: Chinese internet companies spanning interactive media, e-commerce retail and online services; multi-sector thematic",
    ),
    AssignmentSeed(
        "MCHI",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI China ETF: Chinese equities, all sectors",
    ),
    AssignmentSeed(
        "MOO",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "VanEck Agribusiness ETF: farm machinery, fertilizers, animal health and food processors; multi-sector thematic",
    ),
    AssignmentSeed(
        "MTUM",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI USA Momentum Factor ETF: US momentum factor, all sectors (style is tag territory)",
    ),
    AssignmentSeed(
        "QQQ",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Invesco QQQ Trust: Nasdaq-100, 100 largest non-financial Nasdaq companies across sectors",
    ),
    AssignmentSeed(
        "QUAL",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI USA Quality Factor ETF: US quality factor, all sectors",
    ),
    AssignmentSeed(
        "RSP",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Invesco S&P 500 Equal Weight ETF: S&P 500 constituents, equal weighted",
    ),
    AssignmentSeed(
        "SCHD",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Schwab US Dividend Equity ETF: US dividend payers, all sectors",
    ),
    AssignmentSeed(
        "SDOG",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "ALPS Sector Dividend Dogs ETF: five highest-yielding S&P 500 names per sector, equal sector weight",
    ),
    AssignmentSeed(
        "SPHB",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Invesco S&P 500 High Beta ETF: 100 highest-beta S&P 500 stocks, all sectors",
    ),
    AssignmentSeed(
        "SPY",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "SPDR S&P 500 ETF: US large caps across all sectors (D-05 anchor)",
    ),
    AssignmentSeed(
        "USMV",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares MSCI USA Min Vol Factor ETF: US minimum-volatility portfolio, all sectors",
    ),
    AssignmentSeed(
        "VTV",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard Value ETF: US large-cap value, all sectors",
    ),
    AssignmentSeed(
        "VUG",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard Growth ETF: US large-cap growth, all sectors",
    ),
    AssignmentSeed(
        "VWO",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard FTSE Emerging Markets ETF: emerging-market equities, all sectors",
    ),
    AssignmentSeed(
        "VYM",
        "EQ.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard High Dividend Yield ETF: US high-dividend stocks, all sectors",
    ),
    AssignmentSeed(
        "VCR",
        "EQ.CD",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard Consumer Discretionary ETF: US consumer discretionary sector",
    ),
    AssignmentSeed(
        "XHB",
        "EQ.CD",
        SOURCE_REF_FUND_MANDATE,
        "SPDR S&P Homebuilders ETF: equal-weighted homebuilders, home furnishings, appliances, home-improvement retail and building products; homebuilders are about a third, so the mandate only pins Consumer Discretionary",
    ),
    AssignmentSeed(
        "XLY",
        "EQ.CD",
        SOURCE_REF_FUND_MANDATE,
        "Consumer Discretionary Select Sector SPDR: S&P 500 Consumer Discretionary sector",
    ),
    AssignmentSeed(
        "ITB",
        "EQ.CD.DURABLES.HOUSEHOLD",
        SOURCE_REF_FUND_MANDATE,
        "iShares U.S. Home Construction ETF: Dow Jones US Select Home Construction index, majority homebuilders (Household Durables) with building products and home-improvement retail as the minority",
    ),
    AssignmentSeed(
        "XRT",
        "EQ.CD.RETAIL",
        SOURCE_REF_FUND_MANDATE,
        "SPDR S&P Retail ETF: S&P retail select industry index, equal weighted across retail industries",
    ),
    AssignmentSeed(
        "VOX",
        "EQ.COM",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard Communication Services ETF: US communication services sector",
    ),
    AssignmentSeed(
        "XLC",
        "EQ.COM",
        SOURCE_REF_FUND_MANDATE,
        "Communication Services Select Sector SPDR: S&P 500 Communication Services sector",
    ),
    AssignmentSeed(
        "IYZ",
        "EQ.COM.TELECOM",
        SOURCE_REF_FUND_MANDATE,
        "iShares U.S. Telecommunications ETF: US telecom service providers and telecom equipment",
    ),
    AssignmentSeed(
        "XTL",
        "EQ.COM.TELECOM",
        SOURCE_REF_FUND_MANDATE,
        "SPDR S&P Telecom ETF: S&P telecom select industry index, equal weighted",
    ),
    AssignmentSeed(
        "VDC",
        "EQ.CS",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard Consumer Staples ETF: US consumer staples sector",
    ),
    AssignmentSeed(
        "XLP",
        "EQ.CS",
        SOURCE_REF_FUND_MANDATE,
        "Consumer Staples Select Sector SPDR: S&P 500 Consumer Staples sector",
    ),
    AssignmentSeed(
        "RSPG",
        "EQ.EN.ENERGY",
        SOURCE_REF_FUND_MANDATE,
        "Invesco S&P 500 Equal Weight Energy ETF (ticker RSPG since Invesco's 2023 renaming; the instruments row's name says Consumer Staples, which is RSPS). Daily-return correlation over two years: 0.98 with XLE, 0.15 with XLP. Energy has one industry group",
    ),
    AssignmentSeed(
        "URA",
        "EQ.EN.ENERGY",
        SOURCE_REF_FUND_MANDATE,
        "Global X Uranium ETF: uranium miners and nuclear fuel suppliers plus nuclear component makers; the fuel producers dominate, so Energy, above industry because of the component makers",
    ),
    AssignmentSeed(
        "XLE",
        "EQ.EN.ENERGY",
        SOURCE_REF_FUND_MANDATE,
        "Energy Select Sector SPDR: S&P 500 Energy sector, which has one industry group",
    ),
    AssignmentSeed(
        "OIH",
        "EQ.EN.ENERGY.EQUIPSVC",
        SOURCE_REF_FUND_MANDATE,
        "VanEck Oil Services ETF: oilfield services and equipment companies",
    ),
    AssignmentSeed(
        "AMLP",
        "EQ.EN.ENERGY.OILGAS",
        SOURCE_REF_FUND_MANDATE,
        "Alerian MLP ETF: energy infrastructure MLPs (pipelines, storage)",
    ),
    AssignmentSeed(
        "XOP",
        "EQ.EN.ENERGY.OILGAS",
        SOURCE_REF_FUND_MANDATE,
        "SPDR S&P Oil & Gas Exploration & Production ETF: US oil and gas producers",
    ),
    AssignmentSeed(
        "XLF",
        "EQ.FIN",
        SOURCE_REF_FUND_MANDATE,
        "Financial Select Sector SPDR: S&P 500 Financials sector, spans banks, financial services, insurance",
    ),
    AssignmentSeed(
        "KRE",
        "EQ.FIN.BANKS.BANKS",
        SOURCE_REF_FUND_MANDATE,
        "SPDR S&P Regional Banking ETF: US regional banks",
    ),
    AssignmentSeed(
        "VHT", "EQ.HC", SOURCE_REF_FUND_MANDATE, "Vanguard Health Care ETF: US health care sector"
    ),
    AssignmentSeed(
        "XLV",
        "EQ.HC",
        SOURCE_REF_FUND_MANDATE,
        "Health Care Select Sector SPDR: S&P 500 Health Care sector",
    ),
    AssignmentSeed(
        "IHF",
        "EQ.HC.EQUIPSVC.PROVIDERS",
        SOURCE_REF_FUND_MANDATE,
        "iShares U.S. Healthcare Providers ETF: US health insurers, hospitals and care providers",
    ),
    AssignmentSeed(
        "IBB",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_FUND_MANDATE,
        "iShares Biotechnology ETF: US-listed biotechnology companies",
    ),
    AssignmentSeed(
        "XBI",
        "EQ.HC.PHARMA.BIOTECH",
        SOURCE_REF_FUND_MANDATE,
        "SPDR S&P Biotech ETF: S&P biotechnology select industry index, equal weighted",
    ),
    AssignmentSeed(
        "XLI",
        "EQ.IND",
        SOURCE_REF_FUND_MANDATE,
        "Industrial Select Sector SPDR: S&P 500 Industrials sector",
    ),
    AssignmentSeed(
        "ITA",
        "EQ.IND.CAPGOODS.AEROSPACE",
        SOURCE_REF_FUND_MANDATE,
        "iShares U.S. Aerospace & Defense ETF: US aerospace and defense manufacturers",
    ),
    AssignmentSeed(
        "IYT",
        "EQ.IND.TRANSPORT",
        SOURCE_REF_FUND_MANDATE,
        "iShares Transportation Average ETF: Dow Jones Transportation Average, airlines, rails, trucking, air freight",
    ),
    AssignmentSeed(
        "XTN",
        "EQ.IND.TRANSPORT",
        SOURCE_REF_FUND_MANDATE,
        "SPDR S&P Transportation ETF: S&P transportation select industry index across all transport industries",
    ),
    AssignmentSeed(
        "JETS",
        "EQ.IND.TRANSPORT.AIRLINES",
        SOURCE_REF_FUND_MANDATE,
        "U.S. Global Jets ETF: passenger airlines, mostly US carriers",
    ),
    AssignmentSeed(
        "CIBR",
        "EQ.IT",
        SOURCE_REF_FUND_MANDATE,
        "First Trust NASDAQ Cybersecurity ETF: cybersecurity companies spanning software, IT services and communications equipment; the mandate pins the IT sector, not one industry group",
    ),
    AssignmentSeed(
        "VGT", "EQ.IT", SOURCE_REF_FUND_MANDATE, "Vanguard Information Technology ETF: US IT sector"
    ),
    AssignmentSeed(
        "XLK",
        "EQ.IT",
        SOURCE_REF_FUND_MANDATE,
        "Technology Select Sector SPDR: S&P 500 Information Technology sector (D-05 anchor)",
    ),
    AssignmentSeed(
        "SMH",
        "EQ.IT.SEMI.EQUIP",
        SOURCE_REF_FUND_MANDATE,
        "VanEck Semiconductor ETF: US-listed semiconductor companies (D-05 anchor)",
    ),
    AssignmentSeed(
        "IGV",
        "EQ.IT.SOFTWARE.SOFTWARE",
        SOURCE_REF_FUND_MANDATE,
        "iShares Expanded Tech-Software ETF: North American software companies",
    ),
    AssignmentSeed(
        "XLB",
        "EQ.MAT.MATERIALS",
        SOURCE_REF_FUND_MANDATE,
        "Materials Select Sector SPDR: S&P 500 Materials sector, which has one industry group",
    ),
    AssignmentSeed(
        "GDX",
        "EQ.MAT.MATERIALS.METALS",
        SOURCE_REF_FUND_MANDATE,
        "VanEck Gold Miners ETF: gold and silver mining companies",
    ),
    AssignmentSeed(
        "VNQ",
        "EQ.RE",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard Real Estate ETF: US REITs plus real estate management and development",
    ),
    AssignmentSeed(
        "XLRE",
        "EQ.RE",
        SOURCE_REF_FUND_MANDATE,
        "Real Estate Select Sector SPDR: S&P 500 Real Estate sector",
    ),
    AssignmentSeed(
        "RSPU",
        "EQ.UTL.UTILITIES",
        SOURCE_REF_FUND_MANDATE,
        "Invesco S&P 500 Equal Weight Utilities ETF: S&P 500 utilities, one industry group",
    ),
    AssignmentSeed(
        "VPU",
        "EQ.UTL.UTILITIES",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard Utilities ETF: US utilities sector, which has one industry group",
    ),
    AssignmentSeed(
        "XLU",
        "EQ.UTL.UTILITIES",
        SOURCE_REF_FUND_MANDATE,
        "Utilities Select Sector SPDR: S&P 500 Utilities sector, which has one industry group",
    ),
    AssignmentSeed(
        "AGG",
        "FI.BROAD",
        SOURCE_REF_FUND_MANDATE,
        "iShares Core US Aggregate Bond ETF: US investment-grade aggregate (Treasuries, MBS, corporates)",
    ),
    AssignmentSeed(
        "CWB",
        "FI.CONV",
        SOURCE_REF_FUND_MANDATE,
        "SPDR Bloomberg Convertible Securities ETF: US convertible bonds",
    ),
    AssignmentSeed(
        "HYG",
        "FI.CREDIT.HY",
        SOURCE_REF_FUND_MANDATE,
        "iShares iBoxx High Yield Corporate Bond ETF: USD high-yield corporates",
    ),
    AssignmentSeed(
        "LQD",
        "FI.CREDIT.IG",
        SOURCE_REF_FUND_MANDATE,
        "iShares iBoxx Investment Grade Corporate Bond ETF: USD investment-grade corporates",
    ),
    AssignmentSeed(
        "EMB",
        "FI.EM",
        SOURCE_REF_FUND_MANDATE,
        "iShares J.P. Morgan USD Emerging Markets Bond ETF: USD-denominated EM sovereign debt",
    ),
    AssignmentSeed(
        "EMLC",
        "FI.EM",
        SOURCE_REF_FUND_MANDATE,
        "VanEck J.P. Morgan EM Local Currency Bond ETF: local-currency EM government bonds (GBI-EM Global Core)",
    ),
    AssignmentSeed(
        "STIP", "FI.INFL", SOURCE_REF_FUND_MANDATE, "iShares 0-5 Year TIPS Bond ETF: short US TIPS"
    ),
    AssignmentSeed(
        "TIP",
        "FI.INFL",
        SOURCE_REF_FUND_MANDATE,
        "iShares TIPS Bond ETF: US Treasury inflation-protected securities",
    ),
    AssignmentSeed(
        "HYD",
        "FI.MUNI",
        SOURCE_REF_FUND_MANDATE,
        "VanEck High Yield Muni ETF: US high-yield municipal bonds",
    ),
    AssignmentSeed(
        "MUB",
        "FI.MUNI",
        SOURCE_REF_FUND_MANDATE,
        "iShares National Muni Bond ETF: US investment-grade municipal bonds",
    ),
    AssignmentSeed(
        "NAD",
        "FI.MUNI",
        SOURCE_REF_FUND_MANDATE,
        "Nuveen Quality Municipal Income Fund: closed-end fund of US municipal bonds",
    ),
    AssignmentSeed(
        "PFF",
        "FI.PREF",
        SOURCE_REF_FUND_MANDATE,
        "iShares Preferred and Income Securities ETF: US preferred stock",
    ),
    AssignmentSeed(
        "VRP",
        "FI.PREF",
        SOURCE_REF_FUND_MANDATE,
        "Invesco Variable Rate Preferred ETF: variable and floating rate preferreds",
    ),
    AssignmentSeed(
        "BIL",
        "FI.RATES",
        SOURCE_REF_FUND_MANDATE,
        "SPDR Bloomberg 1-3 Month T-Bill ETF: US Treasury bills",
    ),
    AssignmentSeed(
        "EDV",
        "FI.RATES",
        SOURCE_REF_FUND_MANDATE,
        "Vanguard Extended Duration Treasury ETF: long Treasury STRIPS",
    ),
    AssignmentSeed(
        "IEF",
        "FI.RATES",
        SOURCE_REF_FUND_MANDATE,
        "iShares 7-10 Year Treasury Bond ETF: intermediate US Treasuries",
    ),
    AssignmentSeed(
        "SHY",
        "FI.RATES",
        SOURCE_REF_FUND_MANDATE,
        "iShares 1-3 Year Treasury Bond ETF: short US Treasuries",
    ),
    AssignmentSeed(
        "TLT",
        "FI.RATES",
        SOURCE_REF_FUND_MANDATE,
        "iShares 20+ Year Treasury Bond ETF: long US Treasuries",
    ),
    AssignmentSeed(
        "BTAL",
        "MA.ALT",
        SOURCE_REF_FUND_MANDATE,
        "AGF US Market Neutral Anti-Beta Fund: dollar-neutral long low-beta / short high-beta US equities, no net equity-beta mandate",
    ),
    AssignmentSeed(
        "VIXY",
        "VOL.EQUITY",
        SOURCE_REF_FUND_MANDATE,
        "ProShares VIX Short-Term Futures ETF: rolling near-term VIX futures",
    ),
    # Inactive futures and FX pairs: contract underlying
    AssignmentSeed("EURUSD", "CCY.DM", SOURCE_REF_CONTRACT_SPEC, "Euro / US dollar spot pair"),
    AssignmentSeed(
        "GBPUSD", "CCY.DM", SOURCE_REF_CONTRACT_SPEC, "British pound / US dollar spot pair"
    ),
    AssignmentSeed(
        "USDCHF", "CCY.DM", SOURCE_REF_CONTRACT_SPEC, "US dollar / Swiss franc spot pair"
    ),
    AssignmentSeed(
        "USDJPY", "CCY.DM", SOURCE_REF_CONTRACT_SPEC, "US dollar / Japanese yen spot pair"
    ),
    AssignmentSeed("ZC", "CMD.AG", SOURCE_REF_CONTRACT_SPEC, "Corn future"),
    AssignmentSeed("ZS", "CMD.AG", SOURCE_REF_CONTRACT_SPEC, "Soybean future"),
    AssignmentSeed("ZW", "CMD.AG", SOURCE_REF_CONTRACT_SPEC, "Wheat future"),
    AssignmentSeed("CL", "CMD.ENERGY", SOURCE_REF_CONTRACT_SPEC, "WTI crude oil future"),
    AssignmentSeed("NG", "CMD.ENERGY", SOURCE_REF_CONTRACT_SPEC, "Henry Hub natural gas future"),
    AssignmentSeed("HG", "CMD.INDMET", SOURCE_REF_CONTRACT_SPEC, "Copper future"),
    AssignmentSeed("GC", "CMD.PREC", SOURCE_REF_CONTRACT_SPEC, "Gold future"),
    AssignmentSeed("SI", "CMD.PREC", SOURCE_REF_CONTRACT_SPEC, "Silver future"),
    AssignmentSeed(
        "ES", "EQ.BROAD", SOURCE_REF_CONTRACT_SPEC, "E-mini S&P 500 future: S&P 500 index"
    ),
    AssignmentSeed(
        "NQ", "EQ.BROAD", SOURCE_REF_CONTRACT_SPEC, "E-mini Nasdaq-100 future: Nasdaq-100 index"
    ),
    AssignmentSeed(
        "RTY",
        "EQ.BROAD",
        SOURCE_REF_CONTRACT_SPEC,
        "E-mini Russell 2000 future: Russell 2000 index",
    ),
    AssignmentSeed(
        "YM",
        "EQ.BROAD",
        SOURCE_REF_CONTRACT_SPEC,
        "E-mini Dow future: Dow Jones Industrial Average",
    ),
    AssignmentSeed(
        "ZB", "FI.RATES", SOURCE_REF_CONTRACT_SPEC, "30-Year T-Bond future: US Treasury bonds"
    ),
    AssignmentSeed(
        "ZF", "FI.RATES", SOURCE_REF_CONTRACT_SPEC, "5-Year T-Note future: US Treasury notes"
    ),
    AssignmentSeed(
        "ZN", "FI.RATES", SOURCE_REF_CONTRACT_SPEC, "10-Year T-Note future: US Treasury notes"
    ),
    AssignmentSeed(
        "ZT", "FI.RATES", SOURCE_REF_CONTRACT_SPEC, "2-Year T-Note future: US Treasury notes"
    ),
    AssignmentSeed(
        "VIX",
        "VOL.EQUITY",
        SOURCE_REF_CONTRACT_SPEC,
        "CBOE VIX future: 30-day implied volatility of the S&P 500",
    ),
    AssignmentSeed(
        "VX",
        "VOL.EQUITY",
        SOURCE_REF_CONTRACT_SPEC,
        "CBOE VIX future: 30-day implied volatility of the S&P 500",
    ),
)
