#!/usr/bin/env python3
"""Stale K3 HMM Field Cleanup -- todo 236.

Root cause, confirmed via live query + git history (2026-08-03), not guessed: before todo 207
(2026-07-30), `hmm_duration`/`hmm_regime_prob`/`hmm_entropy` were written live, per-bar, by
`FeatureCache`'s now-deleted K3 forward-pass model -- `advance_bar()` incremented
`hmm_duration` unconditionally on every bar; a separate periodic step, `refresh_regime()`, only
reset it to 0 when that K3 model's own label happened to change. For any symbol where the K3
label rarely or never changed (a real risk for a cost-driven, never-BIC-validated approximation,
per todo 207's own framing), the counter simply accumulated "bars processed since cache start,"
never resetting to a meaningful regime-duration value. Todo 207 deleted this entire compute path
outright and made `FeatureFactory.compute()` write all 3 fields as `None` unconditionally --
`regime_writer.py`'s K5-authoritative HMM fit is now the sole writer of real values, in one
atomic UPDATE alongside `regime` (`_compute_symbol_tf`/`_write_regime_results`).

This means the 3 fields split cleanly into two populations:
  - Wherever `regime_writer.py` has successfully labeled a (symbol, tf) cell (`regime IS NOT
    NULL`): all 3 `hmm_*` fields are correct, K5-authoritative values. Confirmed live:
    `max(abs(hmm_duration))` there is 345-2284 bars across all 4 tfs -- entirely plausible.
  - Wherever `regime_writer.py` has never successfully labeled a cell (`regime IS NULL` --
    degenerate model, insufficient obs, etc.): the 3 fields still carry stale garbage from the
    deleted K3 path, since nothing has ever overwritten them for those specific rows. Confirmed
    airtight: 100% of implausible values (e.g. DBA/5m's hmm_duration=367,391, exceeding that
    symbol's own total row count of 367,208) occur exclusively where `regime IS NULL`.

These stale values carry zero informational content -- not merely "large," but generated by a
dead code path whose only reset mechanism was found to be broken the same day it was removed.
Leaving them in the table looking like valid data is the exact "silent wrong answer" CLAUDE.md's
design mandate warns against -- it already contaminated nonlinear_interaction_combiner's training set
once (see todo 236's main resolution; confirmed harmless there via actual feature_importances_,
but the next consumer that doesn't know this history may not be so lucky).

Per this project's Renaissance data-retention discipline: rows are NEVER deleted, `regime` and
every other column is untouched -- only the 3 confirmed-stale fields are nulled, scoped to
`regime IS NULL`, batched per (symbol, tf) pair (so no single UPDATE spans the whole ~10M-row
contamination at once), with an `integrity_monitor` audit record per pair.

Safety (non-negotiable, same convention as ops_known_corrupt_print_cleanup.py): defaults to
--dry-run behavior (report only, zero DB writes). Mutating rows requires --apply.

Usage:
    python scripts/ops/corpus/ops_stale_k3_hmm_fields_cleanup.py
    python scripts/ops/corpus/ops_stale_k3_hmm_fields_cleanup.py --apply
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

import asyncpg
import structlog

from src.config.settings import Settings
from src.core.service_utils import setup_service_logging
from src.observability.metrics import JOB_COMPLETED_TOTAL, flush_and_shutdown_metrics
from src.observability.otel import OTelInitError, init_otel_providers

setup_service_logging("logs/stale_k3_hmm_fields_cleanup.log")
_logger = structlog.get_logger(__name__)

_JOB = "stale-k3-hmm-fields-cleanup"
_MONITOR_TYPE = "stale_k3_hmm_field_cleanup"
_METRIC_NAME = "rows_nulled"

_DISCOVERY_SQL = """
    SELECT symbol, tf, count(*) AS n_stale
    FROM feature_vectors
    WHERE regime IS NULL
      AND (hmm_duration IS NOT NULL OR hmm_regime_prob IS NOT NULL OR hmm_entropy IS NOT NULL)
    GROUP BY symbol, tf
    ORDER BY n_stale DESC
"""

# Scoped to (symbol, tf) -- uses feature_vectors_pkey (symbol, tf, bar_ts) directly, so each
# pair's UPDATE is an efficient index-range operation, not a full-table scan. The WHERE clause
# is identical to _DISCOVERY_SQL's, so what --apply touches is exactly what the dry-run counted.
_CLEANUP_UPDATE_SQL = """
    UPDATE feature_vectors
    SET hmm_duration = NULL, hmm_regime_prob = NULL, hmm_entropy = NULL
    WHERE symbol = $1 AND tf = $2 AND regime IS NULL
      AND (hmm_duration IS NOT NULL OR hmm_regime_prob IS NOT NULL OR hmm_entropy IS NOT NULL)
"""

_AUDIT_INSERT_SQL = """
INSERT INTO integrity_monitor
    (monitor_type, subject, metric_name, metric_value, threshold_value, passed, training_window_end)
VALUES ($1, $2, $3, $4, NULL, true, NULL)
ON CONFLICT (monitor_type, training_window_end, metric_name, COALESCE(subject, ''), evaluated_at) DO NOTHING
"""


async def _discover(pool: asyncpg.Pool) -> list[asyncpg.Record]:
    return await pool.fetch(_DISCOVERY_SQL)


def _render_report(rows: list[asyncpg.Record]) -> str:
    total = sum(r["n_stale"] for r in rows)
    lines = [
        "# Stale K3 HMM Field Cleanup -- Dry-Run Report (todo 236)",
        "",
        f"(symbol, tf) pairs affected: {len(rows)}",
        f"Total rows to be nulled (hmm_duration/hmm_regime_prob/hmm_entropy): {total}",
        "",
        "| symbol | tf | n_stale |",
        "|---|---|---|",
    ]
    for r in rows[:20]:
        lines.append(f"| {r['symbol']} | {r['tf']} | {r['n_stale']} |")
    if len(rows) > 20:
        lines.append(f"| ... | ... | ({len(rows) - 20} more pairs) |")
    return "\n".join(lines)


async def _apply(pool: asyncpg.Pool, rows: list[asyncpg.Record]) -> int:
    total_nulled = 0
    async with pool.acquire() as conn:
        for r in rows:
            symbol, tf, n_stale = r["symbol"], r["tf"], r["n_stale"]
            async with conn.transaction():
                result = await conn.execute(_CLEANUP_UPDATE_SQL, symbol, tf)
                n_updated = int(result.split()[-1])
                await conn.execute(
                    _AUDIT_INSERT_SQL,
                    _MONITOR_TYPE,
                    f"{symbol}:{tf}",
                    _METRIC_NAME,
                    float(n_updated),
                )
            _logger.info(
                "stale_k3_hmm_fields_cleanup.pair_cleaned",
                symbol=symbol,
                tf=tf,
                n_expected=n_stale,
                n_updated=n_updated,
            )
            total_nulled += n_updated
    return total_nulled


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply",
        action="store_true",
        default=False,
        help="Null hmm_duration/hmm_regime_prob/hmm_entropy where regime IS NULL, and write "
        "integrity_monitor audit records. DEFAULT IS DRY-RUN (report only, zero DB writes).",
    )
    return parser.parse_args()


async def _run(args: argparse.Namespace) -> int:
    settings = Settings()
    dsn = settings.database_url.replace("postgresql+asyncpg://", "postgresql://")
    pool = await asyncpg.create_pool(dsn=dsn)
    try:
        rows = await _discover(pool)
        print(_render_report(rows))  # noqa: T201

        if not rows:
            print("\nNothing to clean up.")  # noqa: T201
            return 0

        if not args.apply:
            print(  # noqa: T201
                "\nDRY-RUN MODE (default) -- zero DB writes made. Pass --apply to null these "
                "fields and write integrity_monitor audit records."
            )
            return 0

        total_nulled = await _apply(pool, rows)
        print(
            f"\nAPPLIED: {total_nulled} row(s) had hmm_duration/hmm_regime_prob/hmm_entropy nulled across {len(rows)} (symbol, tf) pairs."
        )  # noqa: T201
        return 0
    finally:
        await pool.close()


def main() -> None:
    args = _parse_args()

    try:
        init_otel_providers(service_name=_JOB)
    except OTelInitError as error:
        _logger.warning("stale_k3_hmm_fields_cleanup.otel_init_failed", error=str(error))

    status = "success"
    try:
        exit_code = asyncio.run(_run(args))
    except Exception as error:
        status = "failure"
        _logger.error("stale_k3_hmm_fields_cleanup.fatal_error", error=str(error))
        raise
    finally:
        JOB_COMPLETED_TOTAL.add(1, {"job": _JOB, "status": status})
        flush_and_shutdown_metrics()

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
